### ISSUE TITLE
Remember Backend Location For API Creation

### ISSUE THREAD

**Issue by m-sterspace** [microsoft/vscode-azurestaticwebapps#107]
When I created my function app, I selected which folder I want my front end and which I want my back end, the default is:
```
  - app
  - api
```
however, I personally prefer:

```
  - frontend
  - backend
```

and selected those folders during the static web app creation process, and it sets up the github actions based on those folders. However, when I go to later add an api to it, it creates the function in the `api` folder, not the specified `backend` folder.

**Comment by nturinski** [comment]
We should stop hard-coding the API folder to be named as 'api'.

Settings are covered by this issue: https://github.com/microsoft/vscode-azurestaticwebapps/issues/36
