### ISSUE TITLE
Cannot install in latest vscode version (1.45.1)

### ISSUE THREAD

**Issue by sushruth** [microsoft/vscode-azurestaticwebapps#115]
Clicking on install currently shows this error - 

![image](https://user-images.githubusercontent.com/2114206/83706216-c3320200-a5cb-11ea-9999-ca6e16766454.png)

**Comment by nturinski** [comment]
Hi @sushruth

Thanks for downloading the Static Web Apps extension.  Unfortunately, it's currently restricted to [VS Code Insiders](https://code.visualstudio.com/insiders/) right now.

However, we should be releasing an update next week that will remove that restriction.

**Comment by sushruth** [comment]
Super.
