### ISSUE TITLE
[Suggestion] Add a "^"(up arrow) in the notification

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#116]
**OS:** Mac/Win 10
**Build:** 20200604.6

**Repro Steps:**

1. F1 --> Extensions: Install from VSIX... --> Select Azure Static Web App vsix.
2. Check the notification.

**Actual:**
There is no "^"(up arrow) in the notification when hover over the notification.
![Screen Shot 2020-06-05 at 4 36 57 PM](https://user-images.githubusercontent.com/62053665/83859657-d1f5f180-a750-11ea-9e31-7ef71c2a0336.png)

**Suggestion:**
Add a "^"(up arrow) in the notification, such as.
![image](https://user-images.githubusercontent.com/62053665/83860167-7ed06e80-a751-11ea-87bb-79c1ecb63055.png)

**Comment by nturinski** [comment]
Closing as an external bug.  We don't control the VS Code UI when an extension is installed.
