### ISSUE TITLE
Experiment with link to docs

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurestaticwebapps#135]
I see this as one (or both) of two options

* A node in the tree when signed in and there are no static web apps
* A new icon in the explorer for a link to docs

 This seems appropriate because Static Web Apps is still pretty new and has some concepts that may be new to some customers. This will also point them to some more advanced scenarios like creating a CRUD API with Cosmos DB.

**Comment by fiveisprime** [comment]
The docs landing page is here: https://docs.microsoft.com/en-us/azure/static-web-apps/

**Comment by jinglouMSFT** [comment]
I'd vote for bullet 2.  Bullet 1's behavior will lead people to guess when the doc node will show up.

**Comment by alexweininger** [comment]
By new icon in the explorer do you mean here? Or a new tree item?

![image](https://user-images.githubusercontent.com/12476526/87210849-e424fb80-c2cb-11ea-9f03-8fcbc964e80a.png)

**Comment by fiveisprime** [comment]
Yeah, I meant there for a new icon. The other option would be a new tree item.

Seems like the icon idea is more popular.
