### ISSUE TITLE
[Suggestion] Add the logs to output when executing "Azure Static Web App: Clone Repo" action

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#138]
**OS:** Win10
**Build Version:** 20200630.1

**Repro Steps:**

1. F1 --> Azure Static Web App: Clone Repo --> Select a Static Web App --> Select Repository Location.
2. Check the output logs.

**Actual:**
There is no output logs.

**Suggestion:**
Add the output logs to "Azure Static Web App: Clone Repo" action.

**Comment by nturinski** [comment]
Since we're leveraging VS Code's git command, the output will be logged there.  I think that users can look there to look at the logs.
