### ISSUE TITLE
[Suggestion] Add a validation when inputting App Setting name

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#140]
**OS:** Win10
**Build Version:** 20200630.1

**Repro Steps:**

1. F1 --> Azure Static Web App: Add New Setting... --> Input "@!#" to App Setting name.
2. Check the result.

**Actual:**
There is an error notification "An error has occurred".
![image](https://user-images.githubusercontent.com/62053665/86334700-2624c080-bc80-11ea-96c2-945750434b25.png)

**Suggestion:**
Add a validation when inputting App Setting name.

Action: staticWebApps.appSettings.add
Error type: 500
Error Message: An error has occurred.

Version: 0.2.1-alpha
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code - Insiders
Product Version: 1.47.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
new StatusCodeError extension.bundle.js:491:1110231
Request.callback extension.bundle.js:491:1109027
Request.RP$callback [as _callback] extension.bundle.js:491:1108075
Request.r._callback.r.callback.r.callback extension.bundle.js:467:4468
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:467:17577
Request.emit events.js:203:13
IncomingMessage.<anonymous> extension.bundle.js:467:16367
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Interestingly, the Portal accepts this as an app setting.

![image](https://user-images.githubusercontent.com/5290572/87732132-f8ac3c80-c780-11ea-8bdb-16435d1c273d.png)

However, when you refresh, it disappears.  I think it's safe to add validation that is the same as Function's app settings since that's what it technically is and they probably have the same constraints.

**Comment by wwlorey** [comment]
Fixed by https://github.com/microsoft/vscode-azurestaticwebapps/pull/361
