### ISSUE TITLE
Add command to change default api subpath setting

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azurestaticwebapps#145]
Might be nice to have a command in this context menu to change the default subpath setting.
![image](https://user-images.githubusercontent.com/12476526/87204000-a66aa780-c2b8-11ea-8dbc-61aa6b9b343f.png)

We could change their `api_location` value in the .yml file for them in this case, as well as the workspace setting.

**Comment by wwlorey** [comment]
We made it a lot easier to view/edit GitHub config values in https://github.com/microsoft/vscode-azurestaticwebapps/pull/321
