### ISSUE TITLE
Subscription is not allowed to register a repo on the Git

### ISSUE THREAD

**Issue by alanhamid** [microsoft/vscode-azurestaticwebapps#148]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.createStaticWebApp
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Web'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 0.2.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.47.1
Language: en

<details>
<summary>Call Stack</summary>

```
new StatusCodeError extension.bundle.js:484:862971
Request.callback extension.bundle.js:484:861767
Request.RP$callback [as _callback] extension.bundle.js:484:860815
Request.r._callback.r.callback.r.callback extension.bundle.js:460:4469
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:460:17578
Request.emit events.js:203:13
IncomingMessage.<anonymous> extension.bundle.js:460:16368
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by wwlorey** [comment]
We need to add a register provider wizard step
