### ISSUE TITLE
Remove "+ Create new Static Web App..." from command list when executing add new setting command

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#150]
**OS:** Win10
**Build Version:** 20200716.1

**Repro Steps:**
F1 --> Azure Static Web Apps: Add New Setting...  --> Check the list.

**Expect:**
There is no "+ Create new Static Web App..." in command list.

**Actual:**
There is a "+ Create new Static Web App..." in command list.
![image](https://user-images.githubusercontent.com/62053665/87762577-f1029b80-c845-11ea-9e9a-422b530405d7.png)

**Comment by nturinski** [comment]
This is actually intended behavior.  While it's unusual, a user may want to add a new app setting to a Static Web App that they haven't created yet (especially if they don't have any SWAs yet)

**Comment by v-mengwe** [comment]
@nturinski Thanks for your update.
I understand what you mean, currently we have the following three ways to create a SWA:
1. Clone the repo, open in your workspace, and create static web app.
2. Create the static app with no workspace opened.
3. Create the static app with a project opened, but there is no GitHub remote associated with it.

Create a SWA through the following steps:
1. F1 --> Azure Static Web Apps: Add New Setting... --> Select "+ Create new Static Web App..." --> Create a SWA through the above three ways.
2. Check the result.

**Actual:**
There is an error.
![image](https://user-images.githubusercontent.com/62053665/88246122-2850cc80-cccc-11ea-8612-b173d901a094.png)

So it is recommended to remove "+ Create new Static Web App..." from command list.

**Comment by nturinski** [comment]
This is because you don't have an API folder associated with the repo.  If you did, this error shouldn't be appearing.  If you try adding a setting to the SWA that was created in these repro steps, do you still have the error?

**Comment by v-mengwe** [comment]
This issue also reproduces when "F1 --> Azure Static Web Apps: Add New Setting... --> Select '+ Create new Static Web App...' --> Create a SWA with the repro which forked from yours(https://github.com/nturinski/ReactSite)."
