### ISSUE TITLE
[Suggestion]Add a command "Show Actions" for Static Web App context menu

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#162]
**OS:** Mac/Windows
**Build:** 20200723.4

**Repro Step:**
	1. Right click a Static Web App.
	2. Check the context menu.

**Actual:**
There is no command "Show Actions" in context menu.
![image](https://user-images.githubusercontent.com/57662131/88367915-7bf01280-cdbf-11ea-826b-dff0561bdea6.png)

**Suggestion:**
Add a command "Show Actions" for Static Web App context menu.

**Comment by nturinski** [comment]
We actually move "Show Actions" from here to the Actions tree node.  If people want to see their actions, they should be able to see most of the information through the explorer now so there's not really a strong need to have this exist on the top level node.
