### ISSUE TITLE
All workflows are not refreshed automatically

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#164]
**OS:** Win10
**Build Version:** 20200727.1

**Repro Steps:**

1. Create a SWA with the repo which forked from https://github.com/nturinski/ReactSite.
2. Drill down the SWA --> Production --> Actions.
3. Check the Actions.

**Expect:**
All workflows are refresh automatically.

**Actual:**
All workflows are not refreshed automatically.
![image](https://user-images.githubusercontent.com/62053665/88642308-e7551f80-d0f2-11ea-99ae-28d4f25085c8.png)

**More Info:**

1. Click the "Refresh" button can fix this issue.
2. This issue also reproduces when executing "Rerun Action..".

**Comment by nturinski** [comment]
This is by-design.  Automatically refreshing can be an expensive task-- especially if you have dozens of polling requests happening at once across multiple extensions.  Most of our extensions follow the pattern of having the user manually refreshing if they want to see the status updates.
