### ISSUE TITLE
Remove "Report an issue" from "Delete Environment…" error dialog

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#174]
**OS:** All
**Build Version:** 20200730.10

**Repro steps:**

1. Create a Static Web App.
2. Right click the "Production" node.
3. Select "Delete Environment...".
4. Check the result.

**Actual:**
Pop up an error "Cannot delete the production environment directly".
![image](https://user-images.githubusercontent.com/57662131/88896151-029f6680-d27c-11ea-80d6-a84710efa4c6.png)

**Suggestion:**
Remove the action "Delete Environment…" from production context menu.

**Comment by nturinski** [comment]
I want to keep the error because it could be confusing to users as to why the delete environment context menu item isn't there.  However we should remove "Report an issue" from the error dialog.
