### ISSUE TITLE
suggestion: improve wording for API section of deployment wizard

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-azurestaticwebapps#182]
With this message, it's not clear that i can leave the `api` section blank. 

![image](https://user-images.githubusercontent.com/1487073/89234573-2119a080-d5a1-11ea-9be3-df3da831d0ab.png)

I pressed `'Escape'` thinking that might do it, but then I had to start the whole process over.  

I actually like the wording in the readme!

`Location of your Azure Functions code. For example, '/api' represents a folder called 'api'. If you don't have an Azure Functions project yet, don't worry! This is optional so just leave this blank.`

**Comment by chrisdias** [comment]
actually, what you have when i am deploying a site that is already on github is better where you have the `Skip for now` option:

![image](https://user-images.githubusercontent.com/1487073/89235446-0a744900-d5a3-11ea-9578-ceea6a76d3be.png)

**Comment by nturinski** [comment]
We can either change the messaging or make it so that when we create a new repo for the user, the options come up with common folder names, manually enter, and skip for now quickPicks.
