### ISSUE TITLE
The icon of workflow will be changed to failed after executing "Cancel Action..."

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#183]
**OS:** Mac/Windows
**Build:** 20200802.1

**Repro Steps:**
1. Create a new environment.
2. Expand the "Actions" node.
3. Right click the workflow -->  Click "Rerun Action...".
4. Execute "Cancel Action..." during the workflow rerunning.
5. Refresh and check the result.

**Expect:**
The icon of workflow is changed as the below:
![image](https://user-images.githubusercontent.com/57662131/89277854-f0586a80-d677-11ea-9c1a-7035c1f5dc4e.png)

**Actual:**
The icon of workflow still is changed to failed as the below:
![image](https://user-images.githubusercontent.com/57662131/89278109-43322200-d678-11ea-9369-33c873ecaa8a.png)
Details in Output:
```
5:22:34 PM: Rerun for action "194538516" has started.
5:22:39 PM: Cancel for action "194538516" has started.
```

**More Info:**
This issue doesn't reproduce on "Production" item.

**Comment by nturinski** [comment]
If you refresh this later, does this still occur?  I don't think the jobs rerun/cancel immediately (since GitHub takes some time to process the request).  Could you see if you refresh it a little later if you get the expected behavior?

**Comment by v-xinda** [comment]
Thanks for your sharing. Verified on the latest build 20200805.1, this issue doesn't reproduce, so close it.
