### ISSUE TITLE
Expand Azure Functions support

### ISSUE THREAD

**Issue by dariagrigoriu** [microsoft/vscode-azurestaticwebapps#185]
Expand Azure Functions support to include .NET Core and Python.

**Comment by nturinski** [comment]
Just to verify, support .NET core and Python in this case is to just enable users to be able to create those function triggers locally, right?  Is the work to support this done in the platform already?

**Comment by anthonychu** [comment]
@nturinski Yes the platform work should be completed to allow .NET and Python function apps. Thanks. /cc @miwebst

**Comment by nturinski** [comment]
So for project languages, we don't support .NET Core by name because it's ambiguous as it could C# or F#.  Would it be sufficient to expand Azure Functions support to include Python and C#?

We only support .NET Core in Functions if you're picking a runtime for the app in Azure.

**Comment by anthonychu** [comment]
Yep this sounds good to me thanks.
