### ISSUE TITLE
The spaces of the value which started with spaces disappear after refreshing

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#187]
**OS:** Win10
**Build:** 20200824.1

**Repro Steps:**
1. Expand the Static Web App.
2. Right click the "Application Settings" node --> Click "Add New Setting..." --> Enter new app setting name 
--> Enter the value "`      1234`".
3. Check the new added setting.
4. Check it again after refreshing.

**Expect:**
Keep the value of new added setting consistent after refreshing.

**Actual:**
The spaces of the value which started with spaces disappear.
![image](https://user-images.githubusercontent.com/57662131/91129106-ffad5f80-e6db-11ea-8c67-a83e742b6d83.png)

**Comment by nturinski** [comment]
Trim the value

**Comment by nturinski** [comment]
Closing as wontfix for the following reason:

> If there's no official docs of the behavior, then it sounds like a bug in the platform rather than an intentional design choice IMO. In that case, I would rather close those 3 issues as "won't fix" rather than perpetuate the bug ourselves. That way, if/when the platform team fixes their bug - we will automatically get the fix.
>
> For example, sometimes app settings are passwords and I could see some random person ending their password with a space.

https://github.com/microsoft/vscode-azuretools/pull/891#discussion_r621594566
