### ISSUE TITLE
The new settings which created from the Production will display under the environment

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#190]
**OS:** Win10
**Build:** 20200830.1

**Repro Steps:**
1. Create a Static Web App.
2. Create an environment for it.
3. Add new settings to Static Web App during the workflows are running.

**Expect:**
The new settings don't display under the "Application Settings" node of environment.

**Actual:**
The new settings display under the "Application Settings" node of environment.
![image](https://user-images.githubusercontent.com/57662131/91694004-852e8500-eb9e-11ea-823b-a0b6226875de.png)

**Comment by nturinski** [comment]
This issue is tracked here: https://github.com/Azure/static-web-apps/issues/86 by the platform team.  I think that this is probably by-design, so I'll close this for now.
