### ISSUE TITLE
There is no workflow under the "Action" node of environment

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#194]
**OS:** Win10
**Build Version:** 20200906.1

**Repro Step:**

1. Create a Static Web App.
2. Create an Environment by the following commands:
```
git checkout -b new
git add .
git commit -m 'api'
git push origin head
```
3. Go to GitHub -> Compare changes between the "master" and "new" branch -> Create a pull request.
4. Check the "Actions" node.

**Expect:**
Display the workflows under the "Actions" node.

**Actual:**
There is no workflow under the "Actions" node.
![image](https://user-images.githubusercontent.com/62053665/92366453-c1765e00-f127-11ea-8346-3cc3a78bb7dc.png)

**Comment by nturinski** [comment]
How long did you wait?  Did you refresh the Actions node?

**Comment by v-mengwe** [comment]
Verified on the latest build 20200908.1, this issue also reproduces after refreshing or waiting about 5 minutes.

**Comment by v-xinda** [comment]
Verified on the latest build 20201103.2. it doesn't reproduce. So close it.
