### ISSUE TITLE
The branch name of the Environment should be "branchname" instead of "GitHubaccount:branchname"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#195]
**OS:** Win10
**Build Version:** 20200906.1

**Repro Step:**

1. Expand a Static Web App.
2. Create an Environment.
3. Check the branches name of Production and Environment.

**Expect:**
The branch name of the Environment is "**branchname**", e.g. `master`.

**Actual:**
The branch name of the Environment is "**GitHubaccount**:**branchname**".
![image](https://user-images.githubusercontent.com/62053665/92373469-ef13d500-f130-11ea-9181-b2aa6c81d878.png)

**Comment by nturinski** [comment]
Sorry, I'm unclear here.  The test environment's branch should _also_ be master?

**Comment by v-mengwe** [comment]
Create an Environment by the following commands:
```
git checkout -b new
git add .
git commit -m 'api'
git push origin head
```
The branch name of the Environment should be "new" instead of "v-mengwe:new".
