### ISSUE TITLE
Fail to open the webpage when executing "Open Repro in GitHub" for the Environment

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#196]
**OS:** Win10
**Build Version:** 20200906.1

**Repro Step:**

1. Expand a Static Web App.
2. Create an Environment.
3. Right click the Environment --> Select "Open Repro in GitHub".
4. Check the result.

**Expect:**
Open the webpage successfully.

**Actual:**
Fail to open the webpage.
![image](https://user-images.githubusercontent.com/62053665/92371309-056c6180-f12e-11ea-9b17-5f1812e79788.png)

**More Info:**

1. Change URL https://github.com/v-mengwe/ReactSite/tree/v-mengwe:new to https://github.com/v-mengwe/ReactSite/tree/new can fix this issue. So, I guess it is caused by the incorrect branch from [195](https://github.com/microsoft/vscode-azurestaticwebapps/issues/195).
2. This issue also reproduces for "Edit configuration..." command.

**Comment by v-xinda** [comment]
Verified on the latest build 20201103.2. it doesn't reproduce. So close it.
