### ISSUE TITLE
The released extension of Azure Functions doesn't support to create HTTP Function

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#202]
**OS:** Mac/Win10
**Build Version:** 20200906.1
**Azure Functions release version:** 0.24.0
**Azure Functions latest build:** 20200915.5

**Repro Steps:**

1. Open a workspace in VS Code.
2. Click "Create HTTP Function...".
3. Pop up a dialog to install the "Azure Functions" extension --> Click "Install".
4. Click "Create HTTP Function..." again.
5. Check the result.

**Expect:**
Succeed to create HTTP Function.

**Actual:**
Fail to create HTTP Function.
![image](https://user-images.githubusercontent.com/57662131/93300239-02a5f680-f829-11ea-8f46-fcccdbef3701.png)

**More Info:**
Succeed to create HTTP Function when installing the latest build of Azure Functions.

**Comment by nturinski** [comment]
Thanks for checking this.  As you said in more info, this relies on the latest build of Functions which we will be releasing this week 😃.  I'll close this as by-design since it'll be resolved by the time we release Static Web Apps.
