### ISSUE TITLE
use existing resource group when in the Azure Sandbox

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-azurestaticwebapps#203]
Microsoft Learn allows a learner to use an Azure sandbox. This is known as a concierge subscription. 

This extension tries to create a resource group. But the sandbox has already created a resource group and does not allow the extension to create another one. So the user is presented with a dialog saying they dont have permission. But it does allow the user to select the existing resource group in the sandbox. (see the image below)

I propose that , ideally, the extension should detect if the subscription is a concierge/sandbox subscription that it should use the existing resource group, saving the learner from having to press the "select existing" button and then select it

![image](https://user-images.githubusercontent.com/1202528/93529512-0493b680-f90a-11ea-9d9e-18135dbb9411.png)

cc @fiveisprime @craigshoemaker

**Comment by craigshoemaker** [comment]
I agree with @johnpapa's suggestion for Learn modules, but I am also wondering about the typical customer scenario as well. 

What if a customer wants to use an existing resource group for their new Static Web App?

The extension should most certainly silently select the concierge resource group in the context of a Learn concierge subscription, but should it also give the developer an opportunity to select an existing resource group?

**Comment by nturinski** [comment]
I agree with @johnpapa on this one as well.  

Regarding picking the resource group for the SWA, it is something that we eventually want to do when we enable a "basic" and "advanced" creation.  Currently, there are 8 prompts to create a SWA which is quite a bit higher than all of our other Azure extensions, and the concern is that we'll confuse and lose users the higher the barrier of entry is.

With a "basic" create scenario, we'll pick defaults (including the rg name) for users to streamline the creation process, whereas "advanced" create will allow users to customize their options.

We're trying to figure out what makes sense as defaults for basic create in this thread: https://github.com/microsoft/vscode-azurestaticwebapps/issues/19.  Please feel free to contribute any ideas that you have 😄.
