### ISSUE TITLE
FrontSmartCoupon

### ISSUE THREAD

**Issue by rbaroudi** [microsoft/vscode-azurestaticwebapps#218]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.createStaticWebApp
Error type: Error
Error Message: User did not consent to login.

Version: 0.4.0
OS: win32
OS Release: 10.0.16299
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
t.ExtHostAuthentication.getSession extensionHostProcess.js:670:641
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Hi @rbaroudi

It seems like you need to give VS Code permission to use your Github account.  Let me know if you need any help doing that.
