### ISSUE TITLE
The notification message is unclear after executing "Upload Local Settings..." action for an environment

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#220]
**OS:** All
**Build Version:** 20201013.1

**Repro Steps:**

1. Create a Static Web App -> Create an Environment.
2. Expand the Environment -> Right click the Application Settings node -> Select "Upload Local Settings..." -> Select a file -> Upload.
3. Check the notification message.

**Expect:**
The notification message is clear.

**Actual:**
The notification message is unclear.
![image](https://user-images.githubusercontent.com/62053665/95964746-b8219500-0e3b-11eb-83b8-de6abf2c6aff.png)

**Comment by nturinski** [comment]
What's the name of your environment in this screenshot?

**Comment by v-mengwe** [comment]
Static Web App version: 20201013.1
The name of environment and notification message as below:
![image](https://user-images.githubusercontent.com/62053665/96082258-79e4ae00-0eed-11eb-92e3-d18e3c553c29.png)

Static Web App version: 20201014.1
The name of environment and notification message as below:
![image](https://user-images.githubusercontent.com/62053665/96082387-b9ab9580-0eed-11eb-9da8-171dfdcec69d.png)

Suggestion:
The notification message "Successfully uploaded settings to `Static Web App name-Production name/Environment name` " is better.

More Info:
This issue also produces during uploading settings.
![image](https://user-images.githubusercontent.com/62053665/96082878-a64cfa00-0eee-11eb-9707-9e5db22d40ee.png)
