### ISSUE TITLE
All workflows are failed after creating a new Static Web App with "Angular" build

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#225]
**OS:** All
**Build Version:** 20201020.2

**Repro Steps:**

1. Right click the Subscription --> Click "Create Static Web App..." --> Enter a name --> Choose a organization --> Choose "ReacSite" repository --> Choose "master" branch --> Choose "Angular" build --> Select a location.
2. Check the result.

**Expect:**
At least one workflow is successful.

**Actual:**
All workflows are failed.

**More Info:**
1. This issue also reproduces for "React/Svelte/Vue.js/Blazor/Gatsby/Hugo/VuePress" build.
2. This issue doesn't reproduce for "Custom" build.

**Comment by nturinski** [comment]
What project are you trying to deploy?  The different builds require different project structures in order to work.  The preset builds are picking the app, api, and app artifact locations for you (the values you are inputting in custom)

**Comment by v-xinda** [comment]
No project opened in workspace.

**Comment by v-xinda** [comment]
Select "Reactsite" repository when creating the SWA. 
Succeed to create a new environment with "Custom" build. Enter the value "app/api" when prompting for app/api location.

**Comment by nturinski** [comment]
The presets are based on the portal's preset list.  You can see them when you create a Static Web App through the portal.  This isn't an issue on the extension, but you need to have the proper framework for each specific preset build.

![image](https://user-images.githubusercontent.com/5290572/95931207-5dc1ff00-0d7d-11eb-9aaf-31c3d4bd41dc.png)
