### ISSUE TITLE
[Suggestion] Add a confirmation dialog after executing command "Show Actions" on Mac

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#226]
**OS:** Mac
**Build Version:** 20201020.2

**Repro Steps:**

1. Expand the Static Web App -->Expand the "Production" node --> Right click the "Actions" node --> Select "Show Actions".
2. Check the result.

**Actual:**
No confirmation dialog pops up.

**Suggestion:**
Add a confirmation dialog after executing command "Show Actions", such as on Windows.
![image](https://user-images.githubusercontent.com/57662131/96685513-cc234480-13af-11eb-9600-a42a37d0452c.png)

**Comment by nturinski** [comment]
This is actually being controlled by VS Code.  The notification has to do with how trusted domains are configured.  I'm not sure if Macs don't have this or if you have configured your VS Code to trust github.com domains.
