### ISSUE TITLE
[Bug] - Extension fails to create SWA for monorepo

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-azurestaticwebapps#227]
I am testing the monorepo support out. I published a SWA from my repo using the vs code extension. Then I changed the workflow file to only build/deploy for the svelte-app folder. Then I tried adding a second SWA using the vs code extension, but I get this error after step 5/6 in the wizard (after I select the folders vue-app and api)Happy to report this to the right repo. 

![image](https://user-images.githubusercontent.com/1202528/96772981-e78f4f00-13b1-11eb-99d1-316127a431d4.png)

I assume the problem here is that the extension may be checking if a SWA exists already for this repo. But with the new monorepo support this should be supported.

**Comment by nturinski** [comment]
Did you happen to leave VS Code idle for a bit?  This has been a recurring issue for a couple of years.  I usually run into it if I've left my window idle for an extended period of time.

As a workaround you could try reloading your window or signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
