### ISSUE TITLE
[Codespace] Need to sign in using GitHub again when refreshing all actions every time

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#234]
**OS:** Win10
**Build Version:** 20201103.1

**Repro Steps:**

1. Create a new static web app and sign in using GitHub -> Drill down the static web app.
2. Right click the "Actions" node -> Click "Refresh". 
3. Check the result.

**Expect:**
Refresh all actions.

**Actual:**
Pop up a dialog to sign in using GitHub again.
![image](https://user-images.githubusercontent.com/57662131/97964132-36e27000-1df3-11eb-8c41-b7437f18404b.png)

**More Info:**
1. This issue also reproduces when expanding the "Actions" node at the first time.
2. This issue also reproduces when executing  "Rerun/Cancel Action" command every time.
3. This issue also reproduces when deleting the static web app/new created environment.
4. This issue also reproduces when selecting the build during creating a static web app.
5. There is an error after clicking "Cancel" when popping up a dialog to sign in using GitHub again.
![image](https://user-images.githubusercontent.com/57662131/97964061-1fa38280-1df3-11eb-9821-15b3e452ccbf.png)

**Comment by nturinski** [comment]
I can't reproduce this issue anymore.  I'm thinking that they fixed the authentication on VS Code Codespaces.  Could you try again and verify that this is still happening?

**Comment by v-xinda** [comment]
Verified on the latest build 20210112.1. This issue doesn't reproduce, so I close it.
