### ISSUE TITLE
The setting name doesn't change automatically after renaming it

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#235]
**OS:** Win10
**Build Version:** 20201103.1

**Repro Steps:**

1. Right click a setting under the "Application Setting" node -> Click "Rename Setting..." -> Enter "test" as the new name.
2. Check the result.

**Expect:**
The setting name changes automatically without any error.

**Actual:**
The setting name doesn't change automatically and an error pops up after waiting about a minute.
![image](https://user-images.githubusercontent.com/57662131/97962673-a3a83b00-1df0-11eb-891e-e2c9fa53de3a.png)
Error type: 500
Error Message: An error has occurred.

**More Info:**
1. This issue also reproduces when deleting/adding/editing the setting.
2. This setting name changes automatically after refreshing.

**Comment by nturinski** [comment]
Is this consistent?  I can't get this to repro on any of my static web apps.

**Comment by v-xinda** [comment]
Firstly, need to add a new setting and name with special characters. Then the above issue reproduces when editing/deleting the other exist settings, you need to wait several minutes. This issue will be fixed after deleting the setting which named with special characters.

**Comment by v-mengwe** [comment]
This issue also reproduces when uploading local setting with special characters name, e.g. 
```
{
"Values":{
   "test!@#":"123"
  }
}
```
![image](https://user-images.githubusercontent.com/62053665/100319618-e5489200-2ffa-11eb-8783-7f4624b5c3f4.png)
