### ISSUE TITLE
Listen for repo changes to update deployments in the tree view

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurestaticwebapps#242]
It was confusing to not see deployment updates in the tree view. And it might not be obvious to the average user that they must refresh to see changes

**Comment by nturinski** [comment]
As much as I want to do this, according to the Git API team, there isn't a listener for the push event.  That makes this a bit of a challenge, but I'll try to figure something out.

**Comment by wwlorey** [comment]
This is not possible without copious polling
