### ISSUE TITLE
[Suggestion] Educate users about how GitHub & Azure fit together to make SWAs work

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurestaticwebapps#243]
Both GitHub and the Azure Portal are mentioned in context menu items in the extension. Not knowing how these pieces fit together made it difficult to understand how the extension worked.

This excerpt from the [tutorial](https://docs.microsoft.com/en-us/azure/static-web-apps/getting-started?tabs=vue) did a good job of succinctly explaining things:
> There are two aspects to deploying a static app. The first provisions the underlying Azure resources that make up your app. The second is a GitHub Actions workflow that builds and publishes your application.

Maybe this could be done via a Welcome page?

**Comment by nturinski** [comment]
I think that this will be best suited for a welcome page experience, which we're pushing back to 0.6.0 while we wait for the new SWA config file to be implemented by the platform team.

**Comment by nturinski** [comment]
Maybe we could create a short video explaining these concepts and throw it in the README/wiki

**Comment by nturinski** [comment]
Not sure if the string changes in the prompt along with the wiki changes quantify us closing this issue.  I'll close it, but open one for using the Walkthrough API which should accomplish this same thing.
