### ISSUE TITLE
Subscription caching

### ISSUE THREAD

**Issue by cfjedimaster** [microsoft/vscode-azurestaticwebapps#245]
I just added the extension, and it noted (correctly) that I do not have a subscription. I followed the link (again, thank you for making that easy), made a subscription, and the extension doesn't see it. I assumed clicking the reload button (round circle) would force the extension to check for subscriptions again. It did not.

**Comment by cfjedimaster** [comment]
I quit VS Code, restarted it, and I was able to see the subscription. Although it DID say no subscriptions at first.

**Comment by nturinski** [comment]
@cfjedimaster Sorry for taking so long connect with you on this.  We're using the Azure Account extension to handle retrieving a user's subscriptions, so I'll let them know about this issue.  Just to clarify:

1. Signed into Azure (with no subscription)
2. Made a subscription
3. Refreshing didn't make the new subscription appear
4. Restarted VS Code, and now the subscription loads

Do you remember how much time occurred between steps 3 and 4?  I know this was over a month ago, so no problem if you don't.

**Comment by cfjedimaster** [comment]
Not sure - I remember focusing on this test so it wasn't a long time.
