### ISSUE TITLE
choose 

### ISSUE THREAD

**Issue by ZachGuoMingyu123** [microsoft/vscode-azurestaticwebapps#258]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.createStaticWebApp
Error type: 406
Error Message: Failed with code "406".

Version: 0.4.0
OS: darwin
OS Release: 20.1.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:600:20318
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Could you please provide detailed repro steps?
