### ISSUE TITLE
Let users copy/paste git repository url to pick org/repo/branch

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurestaticwebapps#261]
Some thoughts on **basic mode**:

**shortest** possible flow, IMO:
1. github repo URL (covers org, repo, even branch if they include it)
2. app location ( we can scan the repo for app, and suggest, but we should not choose it IMO)

I really like not having to enter or and repo separately. GH users are very familiar, I argue, with copying and pasting a GH url. And avoiding two prompts for one ... I think is worth considering. I don't have a problem with the two prompts if you see fit to keep it, but I wanted to toss this up there.

name ... we dont have to ask them for a name. we can give it a name based on the funky name of the SWA URL. WHy not? For basic wizard it would eliminate yet another step. And make it easier to relate the resource to the URL.

**app artifact location**
This folder is different based on the web framework. That's why it must be filled in by the user. But wait ... if we detect the web framework type, we can say "hey, we think this should be the public folder and you are using Svelte" and prompt them with that. And give them the option to change it.

**random thoughts**
1. branch - in basic mode it should use the default branch, IMO.
2. name - we use a generated name based on the SWA URL (ex: snowy-trees)
3. api or functions should be the default (we look for those 2 only)
4. we dont ask for resource group nor location in basic mode

_Originally posted by @johnpapa in https://github.com/microsoft/vscode-azurestaticwebapps/issues/131#issuecomment-695010371_

**Comment by nturinski** [comment]
Most of this was included in the latest release in some form or another.  Thanks @johnpapa for all of the great feedback!

**Comment by johnpapa** [comment]
Thank you!
