### ISSUE TITLE
There is an error occurs after deleting the environment

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#263]
**OS:** Win10
**Build Version:** 20201117.3
**Error type:** NotFound

**Repro Steps:**
1. Create a static web app -> Create an environment for it.
2. Delete the environment.
3. Check the result.

**Expect:**
Succeed to delete the environment without any error.

**Actual:**
There is an error occurs after deleting the environment.
![image](https://user-images.githubusercontent.com/57662131/99494569-3a0d5c80-29ac-11eb-81d1-1767c48885f8.png)
Details in Output:
```
2:39:12 PM: Deleting environment "'test'"...
2:39:28 PM: Successfully deleted environment "'test'".
2:39:29 PM: Error: Cannot find StaticSiteBuild with name 1.
```

**Comment by v-mengwe** [comment]
Verified on the latest build 20210401.8. this issue still reproduces for now.

**Comment by nturinski** [comment]
I think that this should be fixed by https://github.com/microsoft/vscode-azuretools/pull/953

Could you verify this bug please?

**Comment by v-xinda** [comment]
@nturinski  Verified this issue on the latest build 20210713.8, it doesn't reproduce. So I close it.
