### ISSUE TITLE
Do not default API location to /

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurestaticwebapps#266]
Have had a significant number of folks encountering errors because they selected `/` as an API location in our [quickstart](https://docs.microsoft.com/en-us/azure/static-web-apps/getting-started?tabs=vanilla-javascript#create-a-static-web-app). Looks like it may be because we default that location to `/`. I think we should remove that default and only provide the manually select and skip options.

![image](https://user-images.githubusercontent.com/3982077/99897224-a3ab9600-2c4c-11eb-960f-051d5be083af.png)

**Comment by nturinski** [comment]
This PR https://github.com/microsoft/vscode-azurestaticwebapps/pull/222#issuecomment-710435960 moved `Skip for now` and `Manually enter location`.  Do you think that this would be sufficient to prevent people from accidentally selecting /?

**Comment by anthonychu** [comment]
I think that’s better. However I can’t really think of a situation where the API is the root. But let’s see if there is still confusion with the updated version before making more changes. Thanks!

**Comment by nturinski** [comment]
We default users to "api" now.  The reasons being that is the default directory if they create the HTTP trigger within the extension, it won't break the user if they don't have an "api" folder, and it'll automatically work once they do.
