### ISSUE TITLE
[Unstable] There is no error when creating a duplicate Static Web App

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestaticwebapps#272]
**OS:** Win 10/Linux
**Build Version:** 20201125.13

**Repro steps:**
1. Clone the ReactSite repo and open it in VS Code.
2. Create a Static Web App with the default name "v-ruizh-ReactSite".
3. Try to create a new Static Web App with the name "v-ruizh-ReactSite" again.

**Expect:**
An error occurs when creating SWA with the existing Static Web App name.

**Actual:**
There is no error when creating SWA with the existing Static Web App name.
![image](https://user-images.githubusercontent.com/45614674/100340449-3023d300-3016-11eb-8abe-58034488c7bb.png)
Succeed to create duplicate Static Web Apps.
![image](https://user-images.githubusercontent.com/45614674/100340475-3a45d180-3016-11eb-911c-7d8f28343ca2.png)

**More Info:**
This issue is an unstable issue.

**Comment by nturinski** [comment]
Static Web Apps are able to have the same name as long as they are in different resources groups:
![image](https://user-images.githubusercontent.com/5290572/100481346-a4a75200-30a8-11eb-8912-d7206dcf065a.png)
