### ISSUE TITLE
Not able to specify a path to create the API

### ISSUE THREAD

**Issue by sijucm** [microsoft/vscode-azurestaticwebapps#281]
I cannot see where I can give the path where azure function API should be created. I want to specify the path as "src/api" instead of "/api"  It could be that I specified "/" as the path to the api, but I want to change it now to /src. 

I can make it happen by opening the "<application>/src" folder in vs code, but it doesn't look like a good option.

**Comment by nturinski** [comment]
Hi @sijucm

If you go into your VS Code workspace settings, you should be able to set the `azureStaticWebApp.apiSubpath` setting to specify the path that you want to create the API in.  Please let me know if that resolves your issue.
