### ISSUE TITLE
connection time out

### ISSUE THREAD

**Issue by meyyarasu1112** [microsoft/vscode-azurestaticwebapps#285]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.createStaticWebApp
Error type: ETIMEDOUT
Error Message: request to https://management.azure.com/subscriptions/1031056d-5b9e-483c-9b9e-db83bfe527a5/resourcegroups/meyyarasu1112-my-static-web-app?api-version=2019-10-01 failed, reason: connect ETIMEDOUT 40.78.196.33:443

Version: 0.5.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
ClientRequest.<anonymous> extension.js:236:264795
ClientRequest.emit events.js:228:7
ClientRequest.EventEmitter.emit domain.js:475:20
TLSSocket.socketErrorListener _http_client.js:406:9
TLSSocket.emit events.js:223:5
TLSSocket.EventEmitter.emit domain.js:475:20
emitErrorNT destroy.js:92:8
emitErrorAndCloseNT destroy.js:60:3
processTicksAndRejections task_queues.js:81:21
```

</details>

**Comment by nturinski** [comment]
@meyyarasu1112 Could you provide detailed repro steps?  Does this happen consistently?
