### ISSUE TITLE
Not getting all the prompts as per docs

### ISSUE THREAD

**Issue by ahmedsza** [microsoft/vscode-azurestaticwebapps#286]
I am following https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api/4-exercise-static-web-apps?pivots=vue and also looking at the docs at https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestaticwebapps

In those examples they appear to have 6 steps. When I run this, I only get 3 and the option to select the application folder and build output folder is not available. This breaks the lab.. I figured out that I could go change the github action and that would work.

is this by design. If so the docs needs to be changed.. 

FYI- @johnpapa

**Comment by ahmedsza** [comment]
ok, figured out then when the prompt appears with list of frameworks, you can click custom - and then you get the other options.

**Comment by nturinski** [comment]
On our end, we can update the README and include the all the steps in the GitHub Wiki.

**Comment by nturinski** [comment]
GitHub wiki was updated here: https://github.com/microsoft/vscode-azurestaticwebapps/wiki/Creating-a-Static-Web-App
