### ISSUE TITLE
vscode createStaticWebApp   unauthorized

### ISSUE THREAD

**Issue by sachem1** [microsoft/vscode-azurestaticwebapps#289]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.createStaticWebApp
Error type: Error
Error Message: Unauthorized

Version: 0.5.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: zh-cn

<details>
<summary>Call Stack</summary>

```
t.GitHubServer.getUserInfo extension.js:1:28813
processTicksAndRejections task_queues.js:94:5
t.GitHubAuthenticationProvider.tokenToSession extension.js:1:45357
t.GitHubAuthenticationProvider.login extension.js:1:45178
Object.login extension.js:1:42465
t.ExtHostAuthentication._getSession extensionHostProcess.js:694:776
t.ExtHostAuthentication.getSession extensionHostProcess.js:693:961
```

</details>

**Comment by anthonychu** [comment]
Looks like this might be an issue with the VS Code extension. @nturinski could you please take a look?

**Comment by nturinski** [comment]
Could you please provide repro steps?  Is your Azure subscription authorized to create static web apps or resource groups?
