### ISSUE TITLE
Unable to create SWA following included instructions

### ISSUE THREAD

**Issue by coldcanuk** [microsoft/vscode-azurestaticwebapps#290]
Does this occur consistently? 
Repro steps:

1. Installed Extension: Azure Static Web Apps (preview)
2. Began following recipe for "Create your static web app"
3. I click the "+" sign as indicated.
4. I select "Publish local code to a new GitHub repository"
5. I follow the on screen prompts selecting the directory, naming the repo, selecting the language (Blazor), etc. 
6. Azure Static Web Apps also authorizes my GitHub account in order to create the repo. No errors and the account icon in the bottom left of VS Code indicates that I am signed in to GitHub
7. At the end of the prompts the app begins to publish to git and things look like they are about to go right and then at the end I get this error. Not alot of details and I can't find any log that gives me any details as to what failed. VS Code azure tools can clearly see all my azure resource groups, GitHub is connected & it can clearly write to it and create directories. Not sure where to go from here.. hopefully this is a bug and easily fixed :) :) 

Action: staticWebApps.createStaticWebApp
Error type: S
Error Message: Failed to execute git

Version: 0.5.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.53.0
Language: en

**Comment by nturinski** [comment]
Hi @coldcanuk 

Thanks for the very detailed repro steps.  It seems like there's problems with the git steps at the end of publishing.  

In order to publish your repo, we use a git push to push the contents to GitHub.  Could you post your logs from the output channel?  I'd like to see what step that this process is failing at.

**Comment by coldcanuk** [comment]
Hello Nathan,
 I'm with you in wanting to find out exactly where it is failing. That's part of my trouble, lack of data. 
It's possible I'm also being a user and not looking in the right spot...



When you say 'output' you are referencing this window, correct?
![Outlook-fjmgm0qp](https://user-images.githubusercontent.com/8104672/107224993-36ef9e80-69e6-11eb-8fc9-39236aca98b8.png)

Regardless, all four (problems, output, debug console & terminal) show nothing. 

..I wish I would have seen your reply over the weekend! Thanks for the quick response btw!! 
I will try again later today and run fiddler (after work). Maybe something there will show up. 

Cheers,

**Comment by nturinski** [comment]
If you click on the output channel dropdown (where it says Tasks) you should be able to select Azure Static Web Apps from the dropdown menu.

![image](https://user-images.githubusercontent.com/5290572/107274965-028bda80-6a06-11eb-8481-3cd4ce0c2bb9.png)

Hopefully there will be some info there for us to figure out what's going on!

**Comment by coldcanuk** [comment]
Ah HA! the ever elusive drop-down menu that was stabbing you in the eyeball :P Thank you 👍 heh
Unfortunately it yielded a whole-lot-of-nutin' :(

6:50:52 a.m.: Creating new public GitHub repository "RepoSWA"...
6:50:53 a.m.: Created new public GitHub repository "RepoSWA".
6:50:54 a.m.: Initialized repository in local workspace "SWA3".
6:50:55 a.m.: Error: Failed to execute git

**Comment by nturinski** [comment]
Haha, yeah output channel is a really pain to navigate.  Never there when you need it!

Okay, I think I see what's happening at least.  It looks like the repo is getting initialized, but for some reason, we aren't able to commit to it.

In your current workspace/project that you're trying to deploy, are you able to do the following commands?

```
git init
git add .
git commit -m 'Initial commit'
```

If you do that and then try to create the static web app, I think that should resolve the issue.

**Comment by coldcanuk** [comment]
Son of a beehive...... getting closer! :) Your steps appeared to have worked despite my best typo efforts!
I clicked the plus "+" sign next to "Static Web Apps (Preview)" like usual. The only difference is I didn't chose "new repo" I selected existing Repo (RepoSWA4, the one previously created, then the git steps) . I got a new error saying "Branch Not Found". 
So following your logic, my next step is "git branch -M main" and to try again. 
BAH! still says branch not found. This is what "output" shows:
8:10:51 a.m.: Creating new public GitHub repository "RepoSWA4"...
8:10:52 a.m.: Created new public GitHub repository "RepoSWA4".
8:10:53 a.m.: Initialized repository in local workspace "SWA4".
8:10:53 a.m.: Error: Failed to execute git
8:13:50 a.m.: Error: Branch not found
8:21:48 a.m.: Error: Branch not found
<img width="722" alt="almost_there_swa" src="https://user-images.githubusercontent.com/8104672/107642052-5daa1100-6c42-11eb-8b1e-a599ca640c61.png">
So now I'm trying "git remote add origin https://github.com/coldcanuk/RepoSWA4.git" followed by "git push -u origin main"
dang.... and of course work is calling :P hopefully it's just a user/pass thing now ????
PS C:\Users\\OneDrive\VS Code Workspace\swa4> git commit -m 'Initial Commit'
[master (root-commit) 6617934] Initial Commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 .gitignore
PS C:\Users\\OneDrive\VS Code Workspace\swa4> git branch -M main
PS C:\Users\\OneDrive\VS Code Workspace\swa4> git remote add origin https://github.com/coldcanuk/RepoSWA4.git
PS C:\Users\\OneDrive\VS Code Workspace\swa4> git push -u origin main
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/coldcanuk/RepoSWA4.git/'
PS C:\Users\\OneDrive\VS Code Workspace\swa4>

**Comment by nturinski** [comment]
Ah, I think the problem here now is you're using the existing repo.  Existing repo in this case means a repo in GitHub, but the one that you linked is empty.  If you could push up your changes, then it should work!  Otherwise, you can remove the git remote, and click `Publish local code to a new GitHub repository`, and hopefully everything should work that way as well.
