### ISSUE TITLE
error

### ISSUE THREAD

**Issue by phuoctruong11403** [microsoft/vscode-azurestaticwebapps#302]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.deleteStaticWebApp
Error type: AuthorizationFailed
Error Message: The client 'truphu22@evergreen.edu' with object id 'd86414fb-ed9b-48de-a606-5812807f6188' does not have authorization to perform action 'Microsoft.Web/locations/operationResults/read' over scope '/subscriptions/867a58ff-79d9-4d7b-85ca-13b507359667' or the scope is invalid. If access was recently granted, please refresh your credentials.

Version: 0.5.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

**Comment by nturinski** [comment]
It looks like you don't have proper permissions to delete this static web app.  Is this not the case?  If so, could you provide repro steps please.
