### ISSUE TITLE
Azure Static Web Apps (Preview) extension does not appear when installed

### ISSUE THREAD

**Issue by jimblizzard** [microsoft/vscode-azurestaticwebapps#306]
I installed the extension, restarted VS code, but the extension doesn't show up in the list with the other Azure extensions. I've uninstalled, restarted, reinstalled, and restarted code a couple of times. This is on MacOS. Thanks.

**Comment by nturinski** [comment]
Does the extension say that it is properly installed?  

Are you able to see Static Web App commands after hitting F1?
![image](https://user-images.githubusercontent.com/5290572/110022387-b66c4700-7ce0-11eb-9d15-d9ca7e12fd5c.png)


If both of these are correct, then is it collapsed  by chance?  If you right click the Azure window, this context menu should come up:
![image](https://user-images.githubusercontent.com/5290572/110022460-cdab3480-7ce0-11eb-8570-05afcbda3ab2.png)
