### ISSUE TITLE
There is no verification prompt when adding a new setting with a duplicate name

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#313]
**OS:** Win10
**Build Version:** 20210315.5

**Repro Steps:**

1. Create a Static Web App -> Right click the "Application" Settings node -> Add a new setting with name "test" -> Add a new setting with name "test" again
2. Check whether pop up a verification prompt.

**Expect:**
A verification prompt 'App setting name "test" already exists.' pops up.
![image](https://user-images.githubusercontent.com/62053665/111270952-7c4d5e80-866b-11eb-9254-cc3789403a1b.png)

**Actual:**
There is no verification prompt.
![swa](https://user-images.githubusercontent.com/62053665/111272447-9be58680-866d-11eb-92b6-6438f17701ec.gif)

**More Info:**
Refresh can fix this issue.
![swa1](https://user-images.githubusercontent.com/62053665/111272459-a011a400-866d-11eb-8bab-8a39508717b7.gif)

**Comment by wwlorey** [comment]
@v-mengwe We aren't able to repro this issue. Can you try it on your end and see if it's still happening?

**Comment by v-mengwe** [comment]
Verified on the latest build 20210508.12, this issue doesn't reproduce for now, so close it.
