### ISSUE TITLE
issue with git integration

### ISSUE THREAD

**Issue by zenithiti** [microsoft/vscode-azurestaticwebapps#315]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.createStaticWebApp
Error type: S
Error Message: Failed to execute git

Version: 0.5.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

**Comment by nturinski** [comment]
I think this error is stemming from the fact that the project you are using already has a git remote origin.  Could you check `git remote -v` and let me know if the remote already exists?
