### ISSUE TITLE
C:\Users\Habachi Marouane\Desktop\github

### ISSUE THREAD

**Issue by marouanehabachi** [microsoft/vscode-azurestaticwebapps#318]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.createStaticWebApp
Error type: 404
Error Message: Branch not found

Version: 0.5.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1151:1761extension.bundle.js:1151:1761
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment]
Please add repro steps.
