### ISSUE TITLE
Error when Static Web App resource when there's no repositoryUrl

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurestaticwebapps#319]
We've started allowing Static Web Apps to be created without repositoryUrls and other details to support source providers other than GitHub (like Azure DevOps).

![image](https://user-images.githubusercontent.com/3982077/111927060-85c03780-8a6c-11eb-8a0a-3fa68302ddcc.png)

**Comment by nturinski** [comment]
Related to https://github.com/microsoft/vscode-azurestaticwebapps/issues/265

**Comment by nturinski** [comment]
Provide a better error as the internal error doesn't give the customers much information as to why the app is invalid.
