### ISSUE TITLE
Use new Static Web Apps icon

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurestaticwebapps#320]
SVG attached

[01007-icon-Static Apps-Preview.svg.zip](https://github.com/microsoft/vscode-azurestaticwebapps/files/6178736/01007-icon-Static.Apps-Preview.svg.zip)

**Comment by nturinski** [comment]
Are there going to be new icons for the environments?  The huge difference in color is visually unappealing:

![image](https://user-images.githubusercontent.com/5290572/114248963-0b3d5600-994e-11eb-907d-55ce86365515.png)

**Comment by anthonychu** [comment]
Good question. That does look funny. I believe we had to update the main icon last year because it didn't have enough contrast. Can we use a generic icon such as [this one](https://iconcloud.design/browse/Azure%20Icons/Command/3b0f556f7-de64dd68d) for environments?

**Comment by nturinski** [comment]
Oh! Actually the portal is using an updated environments icon
![image](https://user-images.githubusercontent.com/5290572/114428078-99912200-9b70-11eb-95e8-ed2c58c06b9c.png)

I was able to find it in IconCloud 👍
