### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by AmanGoyal31** [microsoft/vscode-azurestaticwebapps#322]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.createStaticWebApp
Error type: Error
Error Message: If you would like to use git features, please enable git in your [settings](command:workbench.action.openSettings?%5B%22git.enabled%22%5D). To learn more about how to use git and source control in VS Code [read our docs](https://aka.ms/vscode-scm).

Version: 0.5.0
OS: win32
OS Release: **10.0.18363**
Product: Visual Studio Code
Product Version: 1.54.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:48:1481677
fulfilled extension.bundle.js:48:1480442
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment]
Please follow the instructions provided to enable git in VS Code. If this doesn't resolve your issue, please add repro steps.
