### ISSUE TITLE
Fail to create a HTTP trigger with .NET 5

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#323]
**OS:** Win10
**Build Version:** 20210325.1
**Function Extension:** 20210325.4

**Repro Steps:**

1. Open an empty folder in VS Code -> Click "Create HTTP Function..." button -> Select C# -> Select .NET 5.
2. Check whether create a HTTP trigger with .NET 5 successfully.

**Expect:**
Succeed to create a HTTP trigger with .NET 5.

**Actual:**
Fail to create a HTTP trigger with .NET 5.
![image](https://user-images.githubusercontent.com/62053665/112571693-8fa6b980-8e23-11eb-82ab-040b83807c9b.png)

**Comment by nturinski** [comment]
@anthonychu Are there any plans for SWA to support .NET 5 triggers (or does it already)?  Trying to figure out if we need to hide this option or figure out why this creation is failing.

**Comment by anthonychu** [comment]
Good point. No immediate plans. The supported Functions runtime versions will remain:

- .NET Core 3.1
- Node.js 12
- Python 3.8

**Comment by anthonychu** [comment]
@fiveisprime Can we bump this up higher in the milestone to ensure it can make it into this release? We don't want folks creating .NET 5 apps.

**Comment by nturinski** [comment]
Will be fixed by using the new API in this PR: https://github.com/microsoft/vscode-azurefunctions/pull/2773/files/4908212f6e918ac7e207a016d5aff1107830ff88..bcde4acbd2131dddde8d42b99e238754cad7376b
