### ISSUE TITLE
consierge

### ISSUE THREAD

**Issue by Syed179** [microsoft/vscode-azurestaticwebapps#331]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.createStaticWebApp
Error type: 500
Error Message: An error has occurred.

Version: 0.5.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.55.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:48:64839
extension.bundle.js:48:1490514extension.bundle.js:48:1490514
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment]
Possibly related to https://github.com/microsoft/vscode-azurestaticwebapps/issues/305

Please make sure that you have admin access to the repository that you are using to create a SWA.

**Comment by nturinski** [comment]
Please provide repro steps.
