### ISSUE TITLE
[GitHub Codespaces] Fail to create a static web app with an error "Unable to fork respository" when publishing local code to a new GitHub repository 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#356]
**OS:** Win 10
**Build Version:** 20210415.7
**Environment:** GitHub Codespaces (local)

**Repro Steps:**
1. F1 --> Click "Create Static Web App...(Advanced)" --> Publish local code to a new GitHub repository --> Choose organization 
--> Select a project --> Enter the name of the new GitHub repository --> Select "public" --> Enter a unique shortname for the new remote --> Enter a name for the new static web app --> create a new resource group --> Choose "Custom" --> Enter "app" --> Enter "api" --> Enter "build" --> Select a region.
2. Pop up a dialog to create a fork as below --> Click "Create Fork" or "NO".
![image](https://user-images.githubusercontent.com/57662131/114986722-eead9a80-9ec6-11eb-9f6f-7799f16b15cf.png)
3. Check whether the static web app is created successfully or not.

**Expect:**
The static web app is created successfully.

**Actual:**
Fail to create a static web app with an error "Unable to fork respository".
![image](https://user-images.githubusercontent.com/57662131/114986704-e6edf600-9ec6-11eb-8388-34dc142b9e5a.png)

**Comment by nturinski** [comment]
@v-xinda The error is actually being thrown by the Git extension.  You can see the error message here: https://github.com/microsoft/vscode/blob/874d19930e3200b4ceb23520f59c99d653d4dc3d/extensions/github/src/pushErrorHandler.ts#L23

We're using their push command, so that's why we're seeing their error handling.  I'm not really sure why the fork would be failing, but we're seeing this because you don't have access to the GitHub repo that you're using.  This is strange because we check for admin access.  Do you know how you're getting to this state?

**Comment by v-xinda** [comment]
@nturinski Hi Nathan, I don't know how to get the state. Can you give me some guides to get the state.

**Comment by nturinski** [comment]
@v-xinda I honestly have no idea how this would happen because we check the project to make sure that the user has admin access to the GitHub project.  If you happen to run into this again, could you document the exact steps you did to make it appear?  This is a very interesting bug 🤔

**Comment by v-xinda** [comment]
@nturinski Verified this issue on the latest build 20210422.7. 
Fail to create an advanced/basic static web app with an error "Git: Failed to execute git".
![create swa](https://user-images.githubusercontent.com/57662131/115841770-b7536680-a44f-11eb-8d28-f366dde096d8.gif)
**Git Version:** 2.31.0

**Comment by nturinski** [comment]
It doesn't appear that you are running from main-- that is this branch: https://github.com/microsoft/vscode-azurestaticwebapps/tree/nat/workspaceEnforced

That being said, if you see this git error, can you check the `Git` output channel?  It should have a much more descriptive reason for the error.

**Comment by v-xinda** [comment]
@nturinski I'm very sorry for verifying the bug with a wrong build.
Verified this issue with the latest main branch build 20210424.1, it still reproduces. Please get details from below:
1. Create a new repository "test-swa" for my GitHub account.
![repo](https://user-images.githubusercontent.com/57662131/115978595-14b3f880-a5b3-11eb-9c9a-ff91648b5508.gif)
2. Open the VS Code and install the **GitHub Codespaces** extension.
3. Navigate to the Remote Explorer --> Create new Codespace with the repository "test-swa".
![swa](https://user-images.githubusercontent.com/57662131/115978482-48dae980-a5b2-11eb-8c8a-e80bf8bc5c27.gif)
4. Install the **Azure Static Web App (Preview)** extension and create a new static web app.
![create1](https://user-images.githubusercontent.com/57662131/115978345-298f8c80-a5b1-11eb-888c-19e17bce7038.gif)

**Comment by wwlorey** [comment]
@v-xinda can you try to reproduce this again with the latest build?

Related: https://github.com/microsoft/vscode-azurestaticwebapps/issues/329

**Comment by nturinski** [comment]
> @v-xinda can you try to reproduce this again with the latest build?
> 
> Related: #329

Actually could you use this build? https://dev.azure.com/ms-azuretools/_apis/resources/Containers/5105878/vsix?itemPath=vsix%2Fvscode-azurestaticwebapps-0.6.1-alpha.vsix  It has better git error handling and that seems to be where the error is coming from.

**Comment by v-xinda** [comment]
@wwlorey  @nturinski Verified this issue with the above build, there is no step to select "Publish local code to a new GitHub repository". So I can not reproduce this issue.
![swa](https://user-images.githubusercontent.com/57662131/116496188-0f1e2180-a8d7-11eb-959f-b9cd2e3298f8.gif)

**Comment by nturinski** [comment]
I think this should be considered resolved now since we're enforcing the workspace.  Also this PR https://github.com/microsoft/vscode-azurestaticwebapps/pull/375 should let us handle the forking logic (whereas the git extension was handling previously)
