### ISSUE TITLE
The resource group is inconsistent between the created one in VS Code and in portal

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#393]
**OS:** All
**Build Version:** 20210508.12

**Repro Steps:**
1. Open the ReactSite project in VS Code.
2. Right click the Concierge Subscription -> Create Static Web App...(Advanced) -> Enter a name -> Click "+Create new resource Group" -> Type a name "nicole-test1" -> Select the Free sku -> Custom -> app -> api -> build -> Select a location.
3. After creating the static web app, open it in portal -> Check the resource group.
4. Check whether the resource group is consistent between the created one in VS Code and in portal.

**Expect:**
The resource group is consistent between the created one in VS Code and in portal.

**Actual:**
The resource group is inconsistent between the created one in VS Code and in portal.
![static](https://user-images.githubusercontent.com/57662131/117780446-37f8cc00-b272-11eb-83fe-2184d1922796.gif)

**Comment by nturinski** [comment]
We can tell the user that the learn resource group was chosen instead due to being on a concierge subscription in the output channel.
