### ISSUE TITLE
The new created environment includes the same app setting which creating from Production

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#394]
**OS:** All
**Build Version:** 20210508.12

**Repro Steps:**
1. Create a new static web app.
2. After creating the static web app, create a new setting for the Production.
3. Create an environment for the static web app.
4. Check whether there is a setting under the "Application Setting" node of the environment.

**Expect:**
There is no setting under the "Application Setting" node of the environment.

**Actual:**
The new created environment includes the same app setting which creating from Production.
![image](https://user-images.githubusercontent.com/57662131/117797718-ead12600-b282-11eb-9cef-2cd634ea2450.png)

**More Info:**
After creating the environment, then create a setting for the Production, the setting doesn't display under the "Application Setting" node of the environment.

**Comment by v-mengwe** [comment]
Verified on the latest build 20210602.8, this issue also reproduces for now.
