### ISSUE TITLE
No subscriptions were found. Set up your account at https://azure.microsoft.com/en-us/free/.

### ISSUE THREAD

**Issue by TuckWai97** [microsoft/vscode-azurestaticwebapps#398]
Does this occur consistently? 
No
Repro steps:

1.I follow the exercise [here](https://docs.microsoft.com/en-us/learn/sports-machine-learning/optimize-basketball-player-rest-breaks/6-create-starter-app) until 'Create a static web app in Azure in Visual Studio Code'
Note: I signed in my account in Azure, that has the subscription with Azure for Student.
2. Select the plus sign of Static Web Apps area to create new static web app
3. Faced error 'No subscription were found ...' 

Version: 0.7.0
OS: Windows 10 Home
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.56.1
Language: en

![Screenshot (1607)](https://user-images.githubusercontent.com/47237045/118095824-2266dc00-b403-11eb-8b20-ad9c91b1ea47.png)
Expected result should be
![Screenshot (1608)](https://user-images.githubusercontent.com/47237045/118095864-314d8e80-b403-11eb-8965-5dbf34d28653.png)

**Comment by nturinski** [comment]
Hi @TuckWai97 

Sorry you're having issues with the extension.  

Have you tried using F1 to use the `Azure: Sign Out` and then `Azure: Sign In` commands?  When you click `Select Subscriptions`, it doesn't generate a list of Azure subscriptions, but throws the error instead?

**Comment by TuckWai97** [comment]
Hi @nturinski , thank you for your help:blush:, it is now solved!:tada: Sorry for reply this late as I am busy with interview for internship and assignments from university recently. Thank you again!

**Comment by nturinski** [comment]
No problem.  Good luck with your interviews @TuckWai97!
