### ISSUE TITLE
Internal error: Expected value to be neither null nor undefined: branchData

### ISSUE THREAD

**Issue by robinhalabicki** [microsoft/vscode-azurestaticwebapps#399]
During Create, Select Subscription, give it a name, 
Problem #1: no option for "Custom" to select location
set build to empty (VUE)

Error generated: Internal error: Expected value to be neither null nor undefined: branchData

**Comment by nturinski** [comment]
After some investigating, I believe that this is due to some hiccup when we create the repo in GitHub for the user.  Even though there GitHub doesn't throw an error, we may need to verify that the branch exists/was created before we continue in our create process.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azurestaticwebapps/pull/415
