### ISSUE TITLE
The "Production" status of the existing static web apps changes by refreshing the tree view during create a new static web app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#403]
**OS:** Win10
**Build Version:** 20210523.1

**Repro Steps:**

1. Open the Reactsite project in the VS Code  -> Create two static web apps successfully, e.g. "elsabas-1", "elsabas-2".
2. Create the third static web app, e.g. "elsabas-3" -> Refresh the tree view during creating the third static web app.
3. Check the "Production" status of static web apps "elsabas-1" and "elsabas-2".

**Expect:**
The "Production" status of static web apps "elsabas-1" and "elsabas-2" remains unchanged.

**Actual:**
The "Production" status of static web apps "elsabas-1" and "elsabas-2" changes.
![image](https://user-images.githubusercontent.com/62053665/119315912-ea845200-bca8-11eb-8d8c-f0d7c8d1eb64.png)

**Comment by nturinski** [comment]
It's because that these are all linked up to the same repo, so the one commit is being pushed to all static web apps.  This is intended behavior.
