### ISSUE TITLE
The location of  "Deleting" becomes next to the "Production" node after refreshing

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#410]
OS: Win10
Build Version: 20210530.1

**Repro Steps:**

1. Create a static web app -> Right click the static web app -> Delete -> Check the location of "Deleting".
2. Refresh the tree view -> Check the location of  "Deleting".
3. Check whether the location of  "Deleting" remains unchanged.

**Expect:**
The location of  "Deleting" remains unchanged.
![image](https://user-images.githubusercontent.com/62053665/120173185-60069a00-c236-11eb-9fc5-4f1ea852d3da.png)

**Actual:**
The location of  "Deleting" becomes next to the "Production" node.
![image](https://user-images.githubusercontent.com/62053665/120173666-d1dee380-c236-11eb-9381-cc9123766147.png)

**Comment by nturinski** [comment]
While this is a bug in our UI, it technically is correct since it is the production build that is getting deleted.  I think that the work to fix this won't be worth the resources, so closing as won't fix.
