### ISSUE TITLE
test

### ISSUE THREAD

**Issue by morita1209** [microsoft/vscode-azurestaticwebapps#417]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.createStaticWebApp
Error type: E
Error Message: Failed to execute git

Version: 0.5.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.48.1
Language: ja

**Comment by nturinski** [comment]
Please provide repro steps.
