### ISSUE TITLE
Git codespaces deployment error

### ISSUE THREAD

**Issue by Yonet** [microsoft/vscode-azurestaticwebapps#419]
Reproduce:

- Use the extention advanced option
- Signed-in to Azure when prompted
- Static Web App resource is created
- Deployment failed with the message in the below image, which doesn't say anything about what to do next.
- Github workflows file is not created 

<img width="392" alt="gitFromCodespace" src="https://user-images.githubusercontent.com/3523671/122509935-86a82d00-cfb9-11eb-8108-6ca8f52b1c71.png">

**Comment by nturinski** [comment]
If you expand that notification, is there more to that error?  I feel like it might be getting cut-off a bit.

Do you happen to know if your GitHub repository has branch protections on it?  Sometimes, especially on your main branch, GitHub will prevent committing directly into main.  You can check these settings in your repo or you could try deploying with a different branch.
