### ISSUE TITLE
[Suggestion] It would be better if the error message is "This workflow is already canceling." when executing "Cancel Action" again

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#433]
**OS:** Win10
**Build Version:** 20210707.4

**Repro Steps:**

1. Expand a new static web app -> Production -> Actions.
2. Right click an action -> Rerun Action -> Right click the same action -> Cancel Action -> Cancel the same action again immediately during canceling the action.
3. Check the error message.

**Actual:**
The error message is unclear.
![image](https://user-images.githubusercontent.com/62053665/124741332-29ffb880-df4e-11eb-9b5b-f3c76b72dcb8.png)

**Suggestion:**
It would be better if the error message is "This workflow is already canceling.", like below:
![image](https://user-images.githubusercontent.com/62053665/124741781-aabeb480-df4e-11eb-9c59-13aae0cb3472.png)

**Comment by nturinski** [comment]
This error message is coming from GitHub.  I think once an action is canceled, it is considered "complete".  The messaging is kind of odd, but I think this is technically correct so I will close it as by-design.
