### ISSUE TITLE
The quotes of the config are inconsistent in the "GitHub Configuration" node and the .yaml file

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#437]
**OS:** Mac
**Build Version:** 20210707.11

**Repro Steps:**
1. Create a static web app.
2. Expand all "GitHub Configuration" nodes -> Check the config.
3. Click the children of all "GitHub Configuration" nodes to open the .yaml file -> Check the config.
4. Check whether the quotes of the config are consistent in the "GitHub Configuration" node and the .yaml file.

**Expect:**
The quotes of the config are consistent in the "GitHub Configuration" node and the .yaml file.
![image](https://user-images.githubusercontent.com/57662131/124886337-b5d51b80-e006-11eb-90b0-f5f04621db07.png)

**Actual:**
The quotes of the config are inconsistent in the "GitHub Configuration" node and the .yaml file.
![image](https://user-images.githubusercontent.com/57662131/124886198-9b02a700-e006-11eb-8891-997f943a555d.png)

**More Info:**
This issue only reproduces for some GitHub Configurations of the static web app.

**Comment by nturinski** [comment]
The way the settings are displayed on the tree item don't take the quotes into consideration.  This is because the yaml file will accept all three as valid settings:
```
app_location : 'app'
api_location: "api"
output_location: output
```

It doesn't seem worth the effort to display all three of these different possibilities.
