### ISSUE TITLE
[Suggestion] It would be better if the config value changes to "" when the config value is blank in the opened .yml files

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#455]
**OS:** Win10
**Build Version:** 20210722.5

**Repro Steps:**

1. Create a static web app using the local project -> Expand the static web app -> Production -> GitHub Configuration -> Click a "GitHub Configuration" child node -> Edit the config value is blank in the opened .yml file, like below: 
    ![image](https://user-images.githubusercontent.com/62053665/126755326-3bc77c3b-838c-4fbb-a671-e02860da4ff9.png)
2. CRTL + S -> Refresh the corresponding "GitHub Configuration". 
3. Check the value of the "output_location".

**Actual:**
The "output_location" value changes to "null".
![image](https://user-images.githubusercontent.com/62053665/126765426-ac9dbdad-a566-4bc7-bdc7-50e63dfe1f3f.png)

**Suggestion:**
It would be better if the "output_location" value changes to `""`.
![image](https://user-images.githubusercontent.com/62053665/126761587-4acf9eef-cc49-493f-ab4d-83a01f486ba6.png)

**More Info:**
In order to distinguish when the config value is "null" in the opened .yml files.
![image](https://user-images.githubusercontent.com/62053665/126765488-cec205a5-1d92-4377-bb6c-b9f317a43452.png)

**Comment by nturinski** [comment]
Need to investigate if having no value (rather than "") is valid yaml file syntax.
