### ISSUE TITLE
Cannot select resource group when generating static website

### ISSUE THREAD

**Issue by weitzhandler** [microsoft/vscode-azurestaticwebapps#469]
Does this occur consistently? Yes
Repro steps:

When trying to create a new static website, there should be a way to select which Resource Group this website should be associated with.

![image](https://user-images.githubusercontent.com/2716316/129044361-ec16d3dd-99e8-4e4c-a4b5-48f4201acde4.png)

Version: 0.7.1
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.59.0
Language: en

**Comment by alexweininger** [comment]
Hi @weitzhandler, using the `Azure Static Web Apps: Create Static Web App... (Advanced)` command, you can select the Resource Group.

You can access this command in two ways:

1. Right-click your subscription, then select the advanced option.
![image](https://user-images.githubusercontent.com/12476526/129089894-e78435fc-e2f0-4ec9-8cf1-6dcbf5839198.png)

2. Open the command palette using <kbd>F1</kbd> or <kbd>Ctrl + Shift + P</kbd>. Then search "Create static web app", and select the "advanced" option.

![image](https://user-images.githubusercontent.com/12476526/129090280-f1373f00-ccde-4238-9eb6-e949e26b5d31.png)

Thanks!

Note:
#457 addresses the confusion around the Basic vs. advanced create commands.

**Comment by wwlorey** [comment]
Please let us know if you run into any more issues
