### ISSUE TITLE
I get :Please enable git" eevn if git is enabled.

### ISSUE THREAD

**Issue by SagarSathe** [microsoft/vscode-azurestaticwebapps#477]

**Comment by SagarSathe** [comment]
If you would like to use git features, please enable git in your settings. To learn more about how to use git and source control in VS Code read our docs.
![image](https://user-images.githubusercontent.com/78426910/129552965-162ad862-51c7-416a-afaf-f9053b7bf5fd.png)

**Comment by nturinski** [comment]
There seems to be another error happening here, but we default to displaying `If you would like to use git features, please enable git in your settings. To learn more about how to use git and source control in VS Code read our docs.`.  There's currently no way for me to verify what this error is, but could you try to reinstall git and reload VS Code?  Maybe something happened to your git path?
