### ISSUE TITLE
Fail to open the workflow file when clicking the child node of GitHub Configuration

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestaticwebapps#501]
**OS:** Win 10
**Build Version:** 20210827.7
**Regression:** Previous Release

**Repro Steps:**
1. Expand one Static Web App -> Production node -> GitHub Configuration -> Click one child node of GitHub Configuration.
2. Check whether the workflow file opens without any error.

**Expect:**
The workflow file opens without any error.

**Actual:**
Fail to open the workflow file with an error.
![image](https://user-images.githubusercontent.com/45614674/131328254-1c2bf7d8-63e2-44ab-b2ca-244688385b0c.png)

**More Info:**
1. The workflow file exists in File Explorer.
2. This issue does not reproduce on Mac and Linux platforms.
3. This issue does not reproduce on the previous released extension v0.7.1.

**Comment by nturinski** [comment]
Tracking external bug here: https://github.com/microsoft/vscode/issues/131925

But we should fix this for the release
