### ISSUE TITLE
Upload app settings fails when there are blocked settings

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurestaticwebapps#509]
![image](https://user-images.githubusercontent.com/3982077/132083927-66ae0c83-f30c-45fe-bf3d-02b91e4a05b3.png)

Static Web Apps does not allow [certain settings](https://docs.microsoft.com/en-us/azure/static-web-apps/apis#constraints).

There are settings that are included by default in function apps that cannot be uploaded. Some are required locally to run (like `FUNCTIONS_WORKER_RUNTIME`). However, looks like the settings API is all-or-nothing and fails if any one setting is restricted. Ideally it should upload the settings that are valid and leave the rest. Or perhaps provide an option to select which settings to upload. As it stands right now, I don't think most settings uploads are likely to fail.

**Comment by wwlorey** [comment]
Our plan is to filter out the prefixes found here: 
https://docs.microsoft.com/en-us/azure/static-web-apps/apis#constraints
