### ISSUE TITLE
Can't create a Static web app with extension for non-default branch

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azurestaticwebapps#510]
I'm trying to create a static web app targeting the "Live" branch. The live branch exists and has already been pushed to GitHub. I get an error when creating the app with the extension but it doesn't give any information about what the error is, just a notification box. 

![image](https://user-images.githubusercontent.com/41597107/132417391-a3f646ee-32c3-4adf-9d15-0f9be5559af5.png)

The SWA is created on Azure and the default branch as the workflow file. Expected it to be on the live branch which is where I was when I created the app, and the pop-up box asked me if I wanted to continue on the Live branch and I said continue.

**Comment by anthonychu** [comment]
Same thing here, except I got a dialog saying it's recommended that I use the default branch. I clicked **Continue** instead of switching to the default branch. *The workflow is still created on the default branch.*

**Comment by alexweininger** [comment]
Fix has been released in version [0.10.0](https://github.com/microsoft/vscode-azurestaticwebapps/releases/tag/v0.10.0)
