### ISSUE TITLE
wiki page is not very welcoming

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-azurestaticwebapps#511]
There is a prominent link in the extension README to the wiki but the nearly blank page doesn't direct the user to more information.
If the user misses the right navigation links, they won't learn more about the extension.
Suggestion: add more text, an image or two, and links to direct the reader to the wiki content and also Static Web App tutorials on docs.microsoft.com or MS Learn.

**Comment by alexweininger** [comment]
Thanks for the feedback! I updated the wiki homepage with page links and resource links. The wiki is still a bit empty but we'll work on adding more content over time.

**Comment by gregvanl** [comment]
Much better! Thanks for doing this.
