### ISSUE TITLE
There is only 1 function in the created Static Web Apps which created based on a project with 3 functions in it

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestaticwebapps#523]
**OS:** Windows 10/Mac
**Build Version:** 20210924.2

**Repro Steps:**
1. Clone the repository "https://github.com/v-ruizh/ReactSite.git" and open this project in VS Code.
2. Create 2 HTTP Functions to this project in VS Code.
3. Create a Static Web Apps in VS Code.
4. Check whether there are 3 functions in Functions node of the new Static Web Apps.

**Expect:**
There are 3 functions in Functions node of the new Static Web Apps.
![image](https://user-images.githubusercontent.com/45614674/134803554-9f2f5a58-4c0f-4f28-a305-d254c8987d14.png)

**Actual:**
There is only 1 function in Functions node of the new Static Web Apps.
![image](https://user-images.githubusercontent.com/45614674/134803524-25c5b766-bda0-4a26-abfc-011fcfefb7e3.png)

**More Info:**
1. This issue does not reproduce after push to remote "original".
2. This issue does not reproduce for a new created environment.
3. This issue also reproduces on the previous released Static Web Apps extension.

**Comment by nturinski** [comment]
Did you commit and push your changes to the master branch?  The static web app is linked to the GitHub remote, not your local git so if you only created it locally, your changes will not propagated.

**Comment by v-ruizh** [comment]
@nturinski I commit my change but not push it to master branch. This issue does not reproduce after pushing my change to master branch. Could we auto-push the change to master branch when creating the Static Web Apps?

**Comment by nturinski** [comment]
No, we don't want to automatically do anything for the user because that would be somewhat confusing and intrusive.  There are many times where a user may commit, but may not necessarily want to push those changes immediately.

This behavior is to be expected for now, and when we include a local developer experience, we will have the triggers update locally automatically.

**Comment by v-ruizh** [comment]
OK, got it. Thanks for your guidance and help.
