### ISSUE TITLE
Clarify region selection

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurestaticwebapps#530]
![image](https://user-images.githubusercontent.com/3982077/135169124-7e1646c1-01f0-4d73-8f43-a560659c97c9.png)

Static Web Apps is a global service. All static content is globally distributed. The region is currently used for 2 things: the location of the function app and where staging environments are created (only production environment is globally distributed).

Please update the title of the box and add a description to match Azure portal:

![image](https://user-images.githubusercontent.com/3982077/135169503-e37a3b55-325f-4c09-a029-ba29a3329580.png)

/cc @simonaco

**Comment by alexweininger** [comment]
Great suggestion. We don't want users thinking their SWA is distributed from a single region.

How does this look?

![image](https://user-images.githubusercontent.com/12476526/135174031-bd6af21f-21a2-47f6-9f4a-160a0dd9a697.png)
