### ISSUE TITLE
Unable to proceed past location question in Simple & Advanced Workflow

### ISSUE THREAD

**Issue by jdhaines** [microsoft/vscode-azurestaticwebapps#536]
I have an issue trying to deploy a static website in the US Gov Cloud using this extension.  I can't seem to get past the location prompt.  In newer versions (0.8.1 & 0.8.0) this is the 4th step in the workflow.  I can't `enter` through it, or progress in any way other than by hitting `esc` to leave the workflow. It seems like this should be supported.  When I connect to the govCloud subscription, it shows in the Static Web Apps extension panel just like the other panels.

![image](https://user-images.githubusercontent.com/3834260/136602272-04702e9b-d68e-4a79-b678-77a77b188f38.png)

If I install an older version such as (0.7.1) the workflow of the prompts is different, but the problem remains.  Nothing typed in the box will make any dropdowns, autocompletes, or react in any way.  In these older versions this is the last step.  

![image](https://user-images.githubusercontent.com/3834260/136597442-165a80e3-a705-4a07-adc9-48fa5b5370df.png)

Any ideas on what could be wrong?  I don't know enough to know if this is a bug or something unique about my use case.

Environment:
Windows 10 Pro- 21H1 - 19043.1237
![image](https://user-images.githubusercontent.com/3834260/136602798-0514b839-9b9f-46ec-8daf-8ce3c6d0f846.png)

**Comment by alexweininger** [comment]
> I guess a minor update with a message if there aren't any locations available might still be useful.

Yeah, that's a great suggestion. Made an issue for it #558

**Comment by alexweininger** [comment]
Suggested change #588  was implemented in #604

**Comment by nturinski** [comment]
I think the issue you listed is unrelated to this PR.  Pretty sure you meant #558
