### ISSUE TITLE
Create SWA - GIT notification is red for remote branch name

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azurestaticwebapps#540]
After creating a new swa for [https://github.com/diberry/swa-test-temp](https://github.com/diberry/swa-test-temp), the VS Code notification showed a red icon indicating an error for the GIT command. I looked at the output for the command and noticed:

```
> git log --oneline --cherry main...main@{upstream} --
fatal: no upstream configured for branch 'main'
> git pull --tags
From https://github.com/diberry/swa-test-temp
   b61feb3..4900e7f  main       -> origin/main
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> main
> git ls-files --stage -- C:\repos\code\temp\20211018\app\tsconfig.json
> git cat-file -s 784403ac9c8e94a5e7fbf7f9c4de59724c1e7a74
> git show --textconv :app/tsconfig.json
> git status -z -u
> git ls-files --stage -- C:\repos\code\temp\20211018\app\tsconfig.json
> git symbolic-ref --short HEAD
> git cat-file -s 784403ac9c8e94a5e7fbf7f9c4de59724c1e7a74
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/main refs/remotes/main
> git show --textconv :app/tsconfig.json
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
``` 

Both the remote and local have the default branch name of "main". I don't think a new SWA should get this error.

**Comment by nturinski** [comment]
Hi @diberry

From the git logs, it seems like you don't have an upstream set up for this repo.  I'm not sure how this could be the case-- maybe the .git file got deleted or we accidentally overwrote your origin somehow?

Could you try running `git pull https://github.com/diberry/swa-test-temp main`?  This should set up tracking information for this branch.

Or you could try `git remote add origin https://github.com/diberry/swa-test-temp main`?

**Comment by diberry** [comment]
@nturinski - I don't think this happened - how could I push to my repo without the remote being available in the local .git?

**Comment by nturinski** [comment]
Unclear to me as well!  

The error reported back from git is indicating that though.  Could you please run `git remote --v` so we can confirm that there is an upstream associated to the repo?

Did you try running `git pull https://github.com/diberry/swa-test-temp main` and see what the output of that is?

Also based off the repo's actions: https://github.com/diberry/swa-test-temp/actions, it seems like it built successfully.  Were you able to resolve this issue?
