### ISSUE TITLE
Failed to deploy a new static web app with a default value of "dist"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#542]
**OS:** Win10
**Build Version:** 20211018.1
**Regression:** Not a Regression

**Repro Steps:**
1. Fork the repo from https://github.com/nturinski/ReactSite -> Execute `git clone https://github.com/v-mengwe/ReactSite` on command to get a ReactSite project -> There is a ReactSite project.
2. Open the ReactSite project in the VS Code -> Click "Create Static Web App..." button -> Select a subscription -> Enter a name for the new static web app -> Select a location -> Choose "React" or "Custom" -> Press enter with default value "app" -> Press enter with default value "**dist**".
    ![image](https://user-images.githubusercontent.com/62053665/137880680-73b940dc-7c77-4c2d-ade0-841d6010eb60.png)
3. Check whether succeed to create a static web app and deploy to it.

**Expect:**
Succeed to create a static web app and deploy to it.

**Actual:**
Succeed to create a static web app, but fail to deploy to it.
![image](https://user-images.githubusercontent.com/62053665/137862940-3ec58ec6-c47e-446c-a6d9-df0d1772da0b.png)

**More Info:**
1. There are successful workflows in the "Actions" when opening the action in GitHub.
    ![Untitled](https://user-images.githubusercontent.com/62053665/137862873-aa5548d0-6f5c-49b8-a5dc-24d343cab5fa.png)
2. Succeed to create a static web app and deploy to it when changing the default value "**dist**" to "**build**".
3. This issue doesn't reproduce for the previous ReactSite project.

**Comment by v-mengwe** [comment]
1. There is a new repository.
2. **Create a Static Web App using "build" when asked to enter the location of build -> Succeed to create a static web app and deploy to it**. (There are **_7_** workflows in the "Actions")![image](https://user-images.githubusercontent.com/62053665/138230781-fb75f05f-6ad8-45c7-8790-6aa7445f38db.png)
3. Create first Static Web App with default value "dist" -> There is a workfolw success. (There are **_15_** workflows in the "Actions")
4. Create second Static Web App with default value "dist" -> Two workflows are successful. (There are **_24_** workflows in the "Actions")
5. Create third Static Web App with default value "dist" -> There is a workfolw success. (There are **_34_** workflows in the "Actions")

**More Info:**
There is no successful workflow if you do not perform this step.
> **Create a Static Web App using "build" when asked to enter the location of build -> Succeed to create a static web app and deploy to it**.

**Comment by nturinski** [comment]
I think the 'dist' is coming from here
https://github.com/v-mengwe/ReactSite/blob/master/.vscode/settings.json#L10

Try deleting that setting and then try to create/deploy a static web app.

**Comment by v-mengwe** [comment]
Thanks for your update, the default value changes to "build" after deleting the setting https://github.com/v-mengwe/ReactSite/blob/master/.vscode/settings.json#L10. 
I checks the repo https://github.com/alexweininger/ReactSite and the setting is in this repo. Is the setting by design?

**Comment by nturinski** [comment]
Yes, this is a setting so that users can control what the defaults should be.  I'll go ahead and close this issue then!

**Comment by v-mengwe** [comment]
Got it, thanks for your update.
