### ISSUE TITLE
[Suggestion] It would be better if add a "Deploy to Static Web App" action in the context menu 

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#543]
**OS:** Win10
**Build Version:** 20211018.1

**Repro Steps:**
Right click a Static Web App -> Check the context menu.

**Actual:**
There is no "Deploy to Static Web App" action in the context menu.
![image](https://user-images.githubusercontent.com/62053665/137892836-54ae121f-5c33-43eb-b542-518dbdfa8811.png)

**Suggestion:**
It would be better if add a "Deploy to Static Web App" action in the context menu. This will be very friendly for a Static Web App that failed to deploy.

**Comment by nturinski** [comment]
Unfortunately, this is currently impossible to do.  When you create the Static Web App, you are setting up the workflow for a specific GitHub repo/branch.  If the build has failed, the workflow file must be edited, committed, and pushed to fix any failures.
