### ISSUE TITLE
[bugbash] Functions extension isn't installed when moving to WSL

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurestaticwebapps#549]
The core problem is that installing the extension in WSL doesn't bring Functions along. Not sure if this is something we can even do something to fix..

1. Install SWA
2. Go to the extension viewlet and install SWA to WSL (at this point only SWA is installed to WSL)
3. Run the initialization command

Result:

![image](https://user-images.githubusercontent.com/1186948/138180580-6754fcb4-a6ea-4865-9c00-2729aa322e80.png)

Expected:  to get the full debug config setup.

Additional details: when I realized what was going on, I switched back to the extension viewlet to install functions. When I install Functions, I get this notification:

![image](https://user-images.githubusercontent.com/1186948/138180744-e98c9eb5-86ea-4cf5-a28b-7d21b85cf1f8.png)

I know that I don't want to click that, but customers may be confused by this since the commands are similar (though the message is specific to Functions).

**Comment by alexweininger** [comment]
@fiveisprime  Is the expected behavior that Functions should automatically be installed whenever a user installs SWA?

I don't think this is the current behavior on any platform.
