### ISSUE TITLE
[bugbash] Change "debug" to "run"

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurestaticwebapps#550]
Another nitpicky one, sorry. Can the "Start debugging app" be changed to "Run the app" or something similar? The dialog should also say something like "Finished setting up for VS Code" or something that matches the command name.

![image](https://user-images.githubusercontent.com/1186948/138180918-640a9661-ad5d-416c-a3c7-aef5a241e273.png)

**Comment by alexweininger** [comment]
I changed the dialog to `Finished setup for running '<app name>'`. And changed the button to `Run <app name>` in #545.
