### ISSUE TITLE
[Suggestion] It would be better to add "environment" word in the popped up dialog information when deleting an environment

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#591]
**OS:** Win10
**Build Version:** 20211221.1
**Regression:** Not a regression

**Repro Steps:**
1. Create a new static web app -> Create a new environment.
2. Right click the environment -> Click "Delete Environment...".
3. Check the popped up dialog.

**Actual:**
There is no "environment" in the popped up dialog information.
![image](https://user-images.githubusercontent.com/57662131/147207880-19202cd4-9355-4886-9db0-2dba40ddf066.png)

**Suggestion:**
It would be better to add "environment" word in the popped up dialog information when deleting an environment, as below.
![image](https://user-images.githubusercontent.com/57662131/147208258-eae0b8c2-318f-4364-a769-02d10ab27cd5.png)

**Comment by alexweininger** [comment]
Good suggestion 👍
