### ISSUE TITLE
[Suggestion] It would be better to add single quote for the setting name in the popped up error message

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#592]
**OS:** Win10
**Build Version:** 20211221.1
**Regression:** Not a regression

**Repro Steps:**
1. Open the **local.settings.json** file -> Add a setting with name "tes  t" (or contains special characters).
![image](https://user-images.githubusercontent.com/57662131/147211349-f28aab42-565e-46d3-969a-b23e5d786560.png)
2. Right click the "Application Settings" -> Click "Upload Local Settings...".
3. Check the popped up error message.

**Actual:**
There is no single quote for the setting name in the popped up error message.
![image](https://user-images.githubusercontent.com/57662131/147211501-9d0d492e-10f6-4813-9181-5c8cb97e6552.png)

**Suggestion:**
It would be better to add single quote for the setting name in the popped up error message, it's convenient for reading.

**Comment by nturinski** [comment]
While I agree with this suggestion, the error is coming directly from Azure so we can't actually change the error message without intercepting and injecting quotes into it so we should close it.
