### ISSUE TITLE
Fail to upload/download local settings for a Static Web App with an error

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#598]
**OS:** Win10
**Build Version:** 20220105.2
**Functions Version:** v1.6.0
**Regression:** Regression (Previous Released)

**Repro Steps:**
1. Make sure the Azure Functions extension is installed.
2. Expand a Static Web App -> Expand "Production".
3. Right click "Application Settings" -> Click " Upload Local Settings...".
4. Check whether succeeds to upload local settings.

**Expect:**
Succeed to upload local settings.

**Actual:**
 Fail to upload local settings with an error.
![image](https://user-images.githubusercontent.com/57662131/148324921-cfa71aa3-f58a-4c26-a8b3-14b5823028cf.png)

**More Info:**
1. This issue also reproduces when clicking "Download Local Settings...".
2. This issue also reproduces when clicking "Create HTTP Function...".

**Comment by alexweininger** [comment]
We've made some changes that will require you to temporarily install the latest Azure Functions extension .vsix before testing Azure Static Web Apps extension.

Before testing Azure Static Web Apps, [download the Azure Functions .vsix from the pipeline](https://dev.azure.com/ms-azuretools/_apis/resources/Containers/5601378/vsix?itemPath=vsix%2Fvscode-azurefunctions-1.6.1-alpha.vsix). And then install it by running the command `Extensions: Install from VSIX...` command, then selecting the downloaded .vsix file.
