### ISSUE TITLE
Debug doesn't recognize SWA CLI 

### ISSUE THREAD

**Issue by digitalclover** [microsoft/vscode-azurestaticwebapps#605]
Whenever I try to run the debug configuration written by this extension, I always get the following warning prompt:
`You must have the Azure Static Web Apps CLI installed to debug your static web app.`

However, I do have the CLI installed globally on my node instance. On one occasion, the debugger still ran after displaying this error. But more often it just doesn't do anything.

Repo created from https://github.com/staticwebdev/angular-basic/generate 

OS: Windows 10
VS Code Instance: WSL Ubuntu-20.04
Node Instance: v14.18.2 (nvm)
SWA CLI Version: 0.8.2

**Comment by alexweininger** [comment]
Thanks for filing the issue!

Could you share the output of the following commands for me?

1. `npm list -g @azure/static-web-apps-cli`

2. `npx --global --no-install swa --version`

The extension specifically looks for the CLI as a globally installed node module. I'll learn more about nvm to see if it could be impacting the way we find the installed CLI.

**Comment by alexweininger** [comment]
Ok, did some investigation with nvm and found that if you install the SWA CLI globally while on one version of node, then switch node versions using nvm, the SWA CLI will no longer be found by npx.

Rough summary of steps taken to produce this:
1. `nvm use <version A>`
2. `npm i -g @azure/static-web-apps-cli`
3. `npx swa --version` --> gives proper output
4. `nvm use <version B>`
5. `npx swa --version` --> can't find the CLI, prompts to install again

**Comment by digitalclover** [comment]
Thanks for your support thus far. 

1. Here's the output to the list command:
```
/home/~/.nvm/versions/node/v14.18.2/lib
└── @azure/static-web-apps-cli@0.8.2
```
2. Here's the output for the npx version command:
`0.8.2`

I'm aware that global installations are encapsulated by which version of node you're using within nvm. `v14.18.2` is also the default version used when opening WSL.

**Comment by alexweininger** [comment]
Are you using the [Remote - WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)? We highly recommend using it when developing with WSL on Windows. I believe using it will fix your issue, since VS Code will be running from within WSL where you've installed the CLI.

**Comment by digitalclover** [comment]
Remote - WSL was installed as a local extension for VS Code at the time I encountered this issue.

**Comment by alexweininger** [comment]
> Yes. Remote - WSL was installed as a local extension for VS Code at the time I encountered this issue.

Ok, 

https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

**Comment by digitalclover** [comment]
The workspace I'm using was open within the WSL environment. However, it seems the extension is now working as expected. I'm not entirely sure what fixed it which most likely means a human error on my part. 

I appreciate your support in this and wish I could have provided a more tangible solution for others to follow who may experience the same issue.

**Comment by alexweininger** [comment]
Glad you were able to get it fixed! And thank you for being so responsive. We will look out for more issues like this to try to provide a better answer for others who experience this.
