### ISSUE TITLE
The webpage displays "This HTTP triggered function executed successfully..." when debugging the "angular-basic" project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#611]
**OS:** Win10
**Build Version:** 20220128.1
**Regression:** Not a regression

**Repro Steps:**

1. Clone https://github.com/staticwebdev/angular-basic -> Open the project in VS Code.
2. Open VS Code terminal and run "npm install" -> Create a TypeScript HTTP endpoint, named "message".
3. Go to the "Run and Debug" menu -> Select "Azure Static Web Apps…" -> Select "SWA: Run angular-basic" -> Click the "Run" button.
4. Navigate to "http://localhost:4280/api/message" in the Chrome window.
5. Check whether the webpage displays "Hello World".

**Expect:**
The webpage displays "Hello World".
![image](https://user-images.githubusercontent.com/62053665/151660257-e7216367-3cbc-408b-af2f-acc3e79ca210.png)

**Actual:**
The webpage displays "This HTTP triggered function executed successfully...".
![image](https://user-images.githubusercontent.com/62053665/151660062-10bcd7f9-441f-4a2b-8ead-3c9396e7bdad.png)

**Comment by wwlorey** [comment]
It looks like the screenshot in our docs were inaccurate - we'll get that fixed. Good find 👍
