### ISSUE TITLE
Fail to execute the command "Azure Static Web Apps: Install or Update Azure Static Web Apps CLI" on Mac&Linux

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#619]
**OS:** M1 Air/Linux
**Build Version:** 20220218.2
**Regression:** Not a regression
**npm version:** 0.8.3

**Repro Steps:**

1. F1 -> Azure Static Web Apps: Install or Update Azure Static Web Apps CLI.
2. Check whether succeeds to execute the command.

**Expect:**
Succeed to execute the command.

**Actual:**
Fail to execute the command.
<img width="804" alt="MicrosoftTeams-image (6)" src="https://user-images.githubusercontent.com/62053665/155119233-1298110f-b683-441a-942c-cedcb83d94a4.png">

**More Info:**

1. This issue also reproduces for the command "Azure Static Web Apps: Uninstall Azure Static Web Apps CLI".
2. It would be better to pop up a link to install it on Mac if this issue is by design.

**Comment by wwlorey** [comment]
@v-mengwe when you encounter this error, what does the message look like? Does the notification provide a button to "view output window"?

**Comment by v-mengwe** [comment]
There is no button in the popped up notification.
<img width="457" alt="MicrosoftTeams-image (9)" src="https://user-images.githubusercontent.com/62053665/155471467-764a94d7-f239-4137-bd5c-cd8536836e75.png">
It would better to execute these commands successfully on Mac/Linux after selecting those commands from command palette.
