### ISSUE TITLE
The next step is to select a environment instead of opening a webpage after executing "Azure Static Web Apps: Browse Site" from command palette

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#631]
**OS:** All
**Build Version:** 20220321.2
**Regression:** Not a regression

**Repro Steps:**
1. F1 -> Click "Azure Static Web Apps: Browse Site" -> Select a Subscription -> Select a Static Web App.
2. Check Whether the next step is to open a webpage.

**Expect:**
The next step is to open a webpage.

**Actual:**
The next step is to select a environment.

**More Info:**

1. This issue reproduces when executing "Azure Static Web Apps: Edit Workflow..." from command palette.
2. This issue does not reproduce when executing "Azure Static Web Apps: View Properties" from command palette.

**Comment by alexweininger** [comment]
Each Environment that exists under a Static Web App can have a different site url, so this behavior is expected. We could improve the UX by defaulting to an Environment if there is only one Environment.
