### ISSUE TITLE
There is an error "Cancelled" when asking to open an URI without any operation

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#632]
**OS:** All
**Build Version:** 20220321.2

**Repro Steps:**

1. Sign out the GitHub account -> Click "Create Static Web App..." button -> Select a subscription -> Allow.
2. Open a webpage in the browser -> Continue -> Allow/Open.
3. Navigate to the opened VS Code window -> Pop up a dialog -> Wait about one minute without any operation.
    ![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/62053665/159684849-016c0f70-2bd7-43ff-a632-4ac98b05bf3e.png)
4. Check whether there is no error.

**Expect:**
There is no error.

**Actual:**
There is an error "Cancelled".
<img width="452" alt="Screen Shot 2022-03-23 at 10 07 20" src="https://user-images.githubusercontent.com/62053665/159683621-e9dcd594-2e6d-4a14-aaca-b51c60b257e1.png">

**More Info:**
Fail to sign in the GitHub account without any errors when continuing with the following steps.

**Comment by alexweininger** [comment]
Timing out for GitHub authentication is done for security reasons. Closing as expected behavior.
