### ISSUE TITLE
Error when attempting to refresh environment node

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurestaticwebapps#651]
![Screen Shot 2022-04-14 at 1 33 25 PM](https://user-images.githubusercontent.com/22795803/163471060-a3054a22-f0a7-4612-bece-e98b6af24dba.png)

This occurred when I attempted to refresh the selected node via the context menu:
![Screen Shot 2022-04-14 at 1 35 03 PM](https://user-images.githubusercontent.com/22795803/163471121-a8122350-5ec3-4d9a-87ac-cf8d2b712bed.png)

**Comment by alexweininger** [comment]
Fixed by #649
