### ISSUE TITLE
[Suggestion] I would expect to see a context menu on the resource type nodes

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-azurestaticwebapps#652]
In this view:
![Screen Shot 2022-04-14 at 1 37 25 PM](https://user-images.githubusercontent.com/22795803/163471411-843d4b03-4134-4212-968f-b341fdf53752.png)

There aren't context menus on resource type nodes right now. Having "refresh" and "create" would be nice to have

**Comment by alexweininger** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/12476526/164541749-a180f0e4-3690-43a0-b558-e58fd22742c0.png)

![image](https://user-images.githubusercontent.com/12476526/164541768-8134098c-5c81-40d8-9948-c54b268c02e7.png)
