### ISSUE TITLE
[Suggestion] It would be better to remove the "+ Create new Resource Group…" option from the command list

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#667]
**OS:** All
**Build Version:** 20220418.2
**Regression:** Not a regression

**Repro Steps:**
1. F1 -> Azure Static Web Apps: Open in GitHub.
2. Check whether there is no "+ Create new Resource Group…" option in the command list.

**Actual:**
1. There is a "+ Create new Resource Group…" option in the command list.
![image](https://user-images.githubusercontent.com/57662131/164390333-09d41ecd-1782-4103-9434-fef5cf3a0a4f.png)
2. An error "No matching resources found" occurs after selecting the "+ Create new Resource Group…" option to create a new resource group.
![image](https://user-images.githubusercontent.com/57662131/164390387-ec6cc147-c364-442c-a7f3-0729dd59b56a.png)

**Suggestion:**
It would be better to remove the "+ Create new Resource Group…" option from the command list.

**More Info:**
This issue also reproduces when executing commands **“Clone Repo...", "Edit Workflow...","Browse Site", "Add New Setting...", "Open GitHub Action Log", "Open in Portal", "Open Repo in GitHub"** and **"View Properties"** from command palette.

**Comment by alexweininger** [comment]
Closed by https://github.com/microsoft/vscode-azureresourcegroups/pull/200

**Comment by v-xinda** [comment]
This issue also reproduces when executing commands **“Clone Repo...", "Edit Workflow...","Browse Site", "Add New Setting...", "Open GitHub Action Log", "Open in Portal", "Open Repo in GitHub"** and **"View Properties"** from command palette.
![image](https://user-images.githubusercontent.com/57662131/165468700-abfe5590-211b-433e-b89c-2f703f77f8dd.png)

**Comment by alexweininger** [comment]
Fixed by #682
