### ISSUE TITLE
There is no "deleting..." status next to the static web app when deleting it

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#668]
**OS:** All
**Build Version:** 20220420.11
**Regression:** Not a regression

**Repro Steps:**
1. Right Click a static web app -> Click "Delete...".
2. Check whether there is a "deleting..." status next to the static web app or not.

**Expect:**
There is a "deleting..." status next to the static web app.
![image](https://user-images.githubusercontent.com/57662131/164412309-6a5cc90d-7f24-43b7-b2f8-bac02cad3ba8.png)

**Actual:**
There is no "deleting..." status next to the static web app.
![image](https://user-images.githubusercontent.com/57662131/164412353-c97dc18c-7b18-4532-8afe-04e1b4bc2ebb.png)

**More Info:**
This issue doesn't reproduce when deleting an environment or application setting.

**Comment by alexweininger** [comment]
Closed by #674
