### ISSUE TITLE
The deleted static web app doesn't disappear automatically after deleting it

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#669]
**OS:** All
**Build Version:** 20220420.11
**Regression:** Not a regression

**Repro Steps:**
1. Right click a static web app -> Click "Delete...".
2. Check whether the deleted static web app disappears automatically after deleting it or not.

**Expect:**
The deleted static web app disappears automatically after deleting it.

**Actual:**
The deleted static web app doesn't disappear automatically after deleting it.
![image](https://user-images.githubusercontent.com/57662131/164417102-1aef9dfc-0b9d-42e4-aa7a-7cf9baa90eee.png)

**More Info:**
1. This issue doesn't reproduce when deleting an environment or application setting.
2. This issue can be fixed by refreshing.

**Comment by alexweininger** [comment]
Closed by #674

**Comment by v-xinda** [comment]
Verified on the latest unified build 20220422.2. It still reproduces, so reopen it.

**Comment by alexweininger** [comment]
Should be fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/222
