### ISSUE TITLE
An error occurs when authorizing GitHub for VSCode

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#67]
**OS:** Win10 & Mac
**Build Version:** [20200514.4](https://dev.azure.com/ms-azuretools/AzCodePrivate/_build/results?buildId=19336&view=results)

**Repro Steps:**
1. Install the Static Web Apps Extension from VSIX.
2. Click "Create Static Web App...".
3. Pop up a prompt as the below. --> Click "Allow" -->Open the GitHub page in browser.
![image](https://user-images.githubusercontent.com/57662131/81913257-4af6a300-9602-11ea-9849-b148d22d9871.png)
4. Authorize GitHub for VSCode -->Continue --> Confirm Password
5. Check the result.

**Expect:**
Authorize successfully.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/57662131/81903922-1af4d300-95f5-11ea-9dfb-2c923ab0c5af.png)

**More Info:**
1. It's successful to authorize GitHub for VSCode at second time.
![image](https://user-images.githubusercontent.com/57662131/81912436-26e69200-9601-11ea-9ddf-12759ce81b3d.png)

2. Back to VS Code, an error dialog pops up.
![image](https://user-images.githubusercontent.com/57662131/81904540-ff3dfc80-95f5-11ea-8a5c-171f5b150e04.png)

**Comment by v-mengwe** [comment]
Verified on the latest build 20200819.1, this issue doesn't reproduce for now, so close it.
