### ISSUE TITLE
[Suggestion] It would be better to update the version of Azure Static Web App extension latest "unified" build

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#670]
**OS:** All
**Azure Resource Extension Build Version:** 20220420.34
**Azure Static Web App extension Build Version:** 20220420.18
**Regression:** Not a regression

**Repro Steps:**

1. Install the Azure Static Web App extension latest "unified" build.
2. Click "Extensions" icon -> There is a update of Azure Static Web App extension. 
    <img width="408" alt="Screen Shot 2022-04-21 at 15 54 09" src="https://user-images.githubusercontent.com/62053665/164407197-03282117-459f-44e5-b8a4-7f057b702308.png">
3. Restart VS Code or reload window.
4. Check whether the Azure Static Web App extension updates to release version automatically.

**Actual:**
The Azure Static Web App extension updates to release version automatically.

**Suggestion:**
It would be better to update the version of Azure Static Web App extension latest "unified" build.

**Comment by alexweininger** [comment]
Fixed in #673
