### ISSUE TITLE
Fail to execute command "Azure Static Web Apps: Open in Portal" from command palette with an error

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#671]
**OS:** All
**Build Version:** 20220420.11
**Regression:** Not a regression

**Repro Steps:**

1. F1 -> Azure Static Web Apps: Open in Portal -> Select a resource group (**the resource group contains a static web app**) -> select a resource.
2. Check whether succeeds to execute command "Azure Static Web Apps: Open in Portal".

**Expect:**
Succeed to execute command "Azure Static Web Apps: Open in Portal".

**Actual:**
Fail to execute command "Azure Static Web Apps: Open in Portal" with an error.
![image](https://user-images.githubusercontent.com/57662131/164422249-5d5faf4d-c23b-4b7c-99f5-228659ff2c25.png)

**Comment by alexweininger** [comment]
This is fixed, and now the command is "Azure Resource Groups: Open in Portal".
