### ISSUE TITLE
Null extension description

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-azurestaticwebapps#679]
When signing in to the Azure Static Web Apps extension I am seeing a lot of references to "null extension description"

![image](https://user-images.githubusercontent.com/35271042/164799570-0882fde1-7087-4ab8-9f48-088fa3d8bafc.png)

![image](https://user-images.githubusercontent.com/35271042/164799579-aba81017-361f-4afb-8ab9-4307c41a6e56.png)

![CleanShot 2022-04-22 at 14 40 40@2x](https://user-images.githubusercontent.com/35271042/164799630-e38089b9-5c63-423a-8e34-1a44ccec6c6e.png)

**Comment by misolori** [comment]
Just as an FYI, the VS Code team is investigating https://github.com/microsoft/vscode/issues/148043

**Comment by alexweininger** [comment]
Closing as the [VS Code bug](https://github.com/microsoft/vscode/issues/148043) has been fixed.
