### ISSUE TITLE
There is an error in "start angular-basic" terminal when debugging the project

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#687]
**OS:** Win10
**Build Version:** 20220511.1
**CLI Version:** 1.0.0-preview

**Repro Steps:**
1. Clone https://github.com/staticwebdev/angular-basic -> Open the project in VS Code.
2. Open VS Code terminal and run "npm install".
3. Go to the "Run and Debug" menu -> Select "Azure Static Web Apps…" -> Select "SWA: Run angular-basic" -> Click the "Run" button.
4. Check whether there is no error in **start angular-basic** terminal.

**Expect:**
There is no error in **start angular-basic** terminal.

**Actual:**
There is an error in **start angular-basic** terminal.
![image](https://user-images.githubusercontent.com/57662131/168035134-88b0d2b5-f912-4710-970e-f9fb2acf9edc.png)

**More Info:**
1. This issue doesn't reproduce when installing **static-web-apps-cli 0.8.3**.
2. This issue also reproduces for below projects:
https://github.com/alexweininger/vue-basic-api
https://github.com/alexweininger/angular-basic-api
https://github.com/alexweininger/nextjs-basic-api
https://github.com/alexweininger/svelte-basic-api
https://github.com/alexweininger/angular-basic-dotnet
3. This issue doesn't reproduce for the ReactSite project.
https://github.com/alexweininger/ReactSite

**Comment by alexweininger** [comment]
This is caused by the argument being renamed from `--devserver-timeout` to `--server-timeout`. 

I've asked the SWA CLI team if they can revert this change https://github.com/Azure/static-web-apps-cli/pull/437/files#r871557757

**Comment by alexweininger** [comment]
They reverted the change and this has been fixed
