### ISSUE TITLE
Add Next.js (SSR) build preset quick pick option once support is added

### ISSUE THREAD

**Issue by MicroFish91** [microsoft/vscode-azurestaticwebapps#709]
https://github.com/microsoft/vscode-azurestaticwebapps/issues/695

**Comment by Reshmi-Sriram** [comment]
Hi Team, any updates on this? @nturinski @alexweininger

**Comment by nturinski** [comment]
Yes, should we also release Nuxt.js 3? We have a PR for that right here: https://github.com/microsoft/vscode-azurestaticwebapps/pull/741

**Comment by Reshmi-Sriram** [comment]
Yes please!
