### ISSUE TITLE
Add commands for Production and Environment in command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestaticwebapps#73]
**OS:** Windows
**Build Version:** [20200514.4](https://dev.azure.com/ms-azuretools/AzCodePrivate/_build/results?buildId=19336&view=results)

**Repro Steps:**
Check the commands in command palette.

**Expect:**
There are commands for Production and Environment.

**Actual:**
There is no command for Production and Environment.
![image](https://user-images.githubusercontent.com/45614674/82021922-55767280-96be-11ea-8f0d-3462aa23db11.png)

**Comment by nturinski** [comment]
Implement ways to do command palette stuff on environments other than production.
