### ISSUE TITLE
Add Build Preset Item for Nuxt 3

### ISSUE THREAD

**Issue by nuzhat-minhaz** [microsoft/vscode-azurestaticwebapps#732]
Currently, the list includes Next.js and Nuxt.js. We want to change the current Nuxt.js item to be titled as "Nuxt 2" and add another item titled "Nuxt 3".

Please check with @anthonychu for details after my end date 29th July 2022.

**Comment by alexweininger** [comment]
We don't currently have a Nuxt.JS item. Did you want us to only add a Nuxt 3 option, or should we add a new Nuxt 2 option and a Nuxt 3 option?
