### ISSUE TITLE
Update the new language version defaults for Node and .NET APIs

### ISSUE THREAD

**Issue by Reshmi-Sriram** [microsoft/vscode-azurestaticwebapps#735]
@nturinski @alexweininger

**Comment by alexweininger** [comment]
For .NET we currently allow creating .NET 3.1 and .NET 6.0 Functions, and we default to .NET 6.0. We can remove the ability to create .NET 3.1 Functions.

For Node.JS, the only place the runtime version is specified is in the [platform.apiRuntime property of the staticwebapp.config.json file](https://learn.microsoft.com/en-us/azure/static-web-apps/configuration#nodejs). Should we automatically add/edit this property when users create a Node.JS Function?

**Comment by Reshmi-Sriram** [comment]
Do we not default Node.js to any stack as of today? What happens if a user does not have an apiRuntime property set at all? We need to make that default to 16. We needn't automatically edit the config, we can always ask them to.
CC// @vivekjilla

**Comment by alexweininger** [comment]
> Do we not default Node.js to any stack as of today? What happens if a user does not have an apiRuntime property set at all?

@Reshmi-Sriram any updates regarding these questions? The default platforms aren't specified on the [docs](https://learn.microsoft.com/en-us/azure/static-web-apps/configuration#platform).

**Comment by Reshmi-Sriram** [comment]
Hey @alexweininger,
Just had a quick call with @vivekjilla and understood how things work for Node. So since we use GHActions to do the build and deploy, we wll be relying on Oryx for the build, and the SWA code will take care of setting the Node default, so we don't have to worry about this on the VSCode side of things. 
Now that the .NET Core 3.1 changes are in, I think we can close this ticket. Thanks! :)
