### ISSUE TITLE
The actions are truncated in production node

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurestaticwebapps#747]
**OS:** Win10/Linux
**Build Version:** 20221011.6
**VS Code Version** :1.72.1

**Repro Step:**

1. Create a Static Web App -> Expand the static web app -> Expand "Production" -> Expand "Actions".
2. Check Whether the actions show well in production node.

**Expect:**
 The actions show well in production node.

**Actual:**
The actions are truncated in production node.
![image](https://user-images.githubusercontent.com/107091828/195290338-5a876a74-4515-492b-b49b-a0c8b39d0ce2.png)

**More Info:**
 1. The actions show well in environment node when creating an environment on Win10 and Linux OS.
 2. The issue doesn't reproduce on Vs Code version 1.71.2.

**Comment by alexweininger** [comment]
Duplicate of #744
