### ISSUE TITLE
After Signing into azure with tenant and static web app nothing comes under resource.

### ISSUE THREAD

**Issue by MasterThreadInf** [microsoft/vscode-azurestaticwebapps#754]
Does this occur consistently? 
Yes and I followed https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#setup-your-azure-account 
multiple times but still static web app is not been created. 

Version: 0.11.3
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.72.2
Language: en

**Comment by nturinski** [comment]
Hi @MasterThreadInf

Are you able to create successfully and nothing gets listed under resources? 
Could you provide a screenshot of what your Resources view looks like?
Are you able to create a Static Web App through the [Azure Portal?](https://ms.portal.azure.com/#home)

**Comment by MasterThreadInf** [comment]
> Hi @MasterThreadInf
> 
> Are you able to create successfully and nothing gets listed under resources? Could you provide a screenshot of what your Resources view looks like? Are you able to create a Static Web App through the [Azure Portal?](https://ms.portal.azure.com/#home)

Hi @nturinski 

I'm newbee to azure and I didn't had subscription to azure even the free one with visual studio.  Now I signed up for free account for testing. Yes, now I'm able to create static web app and everything looks plausible. 

Thank you :)
