### ISSUE TITLE
Add support for Node.js 18 and .NET 7

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurestaticwebapps#758]
Discussed in our sync. Trying to land this before the Thanksgiving break.

**Comment by alexweininger** [comment]
We shouldn't need to change anything in the extension in order to support new versions of Node.js. The Node.js version used at app runtime is decided via the staticwebapp.config.json file if provided. See https://github.com/microsoft/vscode-azurestaticwebapps/issues/735 for more details.
