### ISSUE TITLE
Let users specify .NET version when adding an HTTP Function

### ISSUE THREAD

**Issue by alexweininger** [microsoft/vscode-azurestaticwebapps#761]
See #759 for details, but tl;dr is we need to not only allow creating .NET 7.0 Functions, we also need to give users a choice between .NET 6.0 and 7.0 instead of defaulting to 6.0.

**Comment by thomasgauvin** [comment]
Now with .NET 8, we should allow users the ability to choose .NET 8, and default to .NET 8 (currently we default to .NET 6) @nturinski
