### ISSUE TITLE
No setting is added to Application Settings list after uploading local settings

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestaticwebapps#77]
OS: Windows
Build Version: [20200514.4](https://dev.azure.com/ms-azuretools/AzCodePrivate/_build/results?buildId=19336&view=results)

Repro Steps:
1. Right click the Application Settings node for a environment->Upload Local Settings...
2. Check the application settings after uploading.

Expect:
The uploaded settings are added to application settings list.

Actual:
No setting is added to Application Settings list after uploading local settings.
![image](https://user-images.githubusercontent.com/45614674/82028259-f74e8d00-96c7-11ea-94fe-f411a5a84eeb.png)

**Comment by nturinski** [comment]
Related to https://github.com/microsoft/vscode-azurestaticwebapps/issues/89
