### ISSUE TITLE
"git model not found" Source: Azure Static Web App (Extension)

### ISSUE THREAD

**Issue by Mustak-BIT** [microsoft/vscode-azurestaticwebapps#770]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.createStaticWebApp
Error type: Error
Error Message: Git model not found

Version: 0.11.3
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.73.1
Language: en

<details>
<summary>Call Stack</summary>

```
s.getAPI main.js:2:1017691
extension.bundle.js:2:3529066extension.bundle.js:2:3529066
fulfilled extension.bundle.js:2:3527866
```

</details>

**Comment by alexweininger** [comment]
Do you have Git installed? VS Code throws this error when git is not installed.

**Comment by MicroFish91** [comment]
Closing due to lack of response, we can reopen if you're still experiencing this issue.
