### ISSUE TITLE
Heading Missing (enhancement)

### ISSUE THREAD

**Issue by samipak458** [microsoft/vscode-azurestaticwebapps#775]
My name is Muhammad Samiullah and I'm **Microsoft Learn Student Ambassadors**. I'm going through the website and I feel like there is a need of **Prerequisites or Requirements for Static Web App** heading.

## Issue decryption
Issue on: [Extension Azure Static WebApp](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestaticwebapps)
Before heading **Run and Debug Your Static Web App** there is a need of a heading **Prerequisites or Requirements for Static Web App** which will help users in understanding the requirements of Static Web App and make the user experience better.

**Suggestion to add Prerequisites or Requirements for Static Web App like this**

![image](https://user-images.githubusercontent.com/52650290/207511303-4829c571-9fe1-4b6b-9aa6-8907070a821a.png)

**Comment by alexweininger** [comment]
The prerequisites are located in the [linked guide](https://github.com/microsoft/vscode-azurestaticwebapps/wiki/Guide:-Debugging-a-Static-Web-App-with-VS-Code) in that section of the readme.

<img width="884" alt="Screenshot 2022-12-14 at 3 48 32 PM" src="https://user-images.githubusercontent.com/12476526/207739743-b95faba1-82a1-4d66-a0fa-417699510140.png">
