### ISSUE TITLE
Fail to execute the command "Azure Static Web Apps: Install or Update Azure Static Web Apps CLI" on Mac & Linux

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestaticwebapps#782]
**OS:** M1/Linux
**Build Version:** 20230119.3
**Regression:** Not a regression

**Repro Steps:**
1. F1 -> Azure Static Web Apps: Install or Update Azure Static Web Apps CLI.
2. Check whether succeeds to execute the command.

**Expect:**
Succeed to execute the command.

**Actual:**
Fail to execute the command.
![image](https://user-images.githubusercontent.com/45614674/213666438-86f62d96-8aa1-4b9a-ad9d-e12b2b14763c.png)
![image](https://user-images.githubusercontent.com/45614674/213666480-7fb506d2-88dd-4f09-904c-4776f159996f.png)

**More Info:**
1. This issue does not reproduce on Windows.
2. Succeed to install the Azure Static Web Apps CLI with the same command which add "sudo" manually.
3. This issue also reproduces when executing command "Azure Static Web Apps: Uninstall Azure Static Web Apps CLI".

**Comment by MicroFish91** [comment]
The error is pretty clear about needing to rerun the command with 'sudo'.  This error only occurs when npm isn't installed in the correct directory for privilege purposes.
