### ISSUE TITLE
Successfully deleted SWA still appears in the Resources view 

### ISSUE THREAD

**Issue by motm32** [microsoft/vscode-azurestaticwebapps#783]
**V2 forward compatibility testing**

After deleting a SWA and receiving a `Delete Static Web App... succeeded` Activity Log the SWA still appears in the tree view. Once you refresh, the SWA disappears as expected.

**Comment by alexweininger** [comment]
I checked Virtual Machines and this issue reproduces there too. I think I can fix this easily by adding some compat shim stuff in RGs

**Comment by alexweininger** [comment]
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/529
