### ISSUE TITLE
web-site

### ISSUE THREAD

**Issue by Andreads2606** [microsoft/vscode-azurestaticwebapps#796]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.activate
Error type: string
Error Message: Timed out waiting for authentication provider to register

Version: 0.11.4
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.0
Language: de

**Comment by MicroFish91** [comment]
It sounds like this person might have a similar issue that they found a solution for.  Could you please try following these steps and see if it resolves your issue: https://github.com/microsoft/vscode-pull-request-github/issues/3469#issuecomment-1109584285

If not could you please provide more specific repro steps, thank you 🙂
