### ISSUE TITLE
Issue with Az Static WebApp

### ISSUE THREAD

**Issue by huynguyen305** [microsoft/vscode-azurestaticwebapps#806]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.activate
Error type: string
Error Message: Timed out waiting for authentication provider to register

Version: 0.11.4
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.76.2
Language: en

**Comment by MicroFish91** [comment]
Could you please add repro steps and does this reproduce every time?
