### ISSUE TITLE
[Codespaces] The deleted app setting doesn't auto disappear after executing "Azure Static Web Apps: Delete Setting..." from command palette

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#807]
**Environment:** GitHub Codespaces (Local)
**Build Version:** 20230327.1
**Regression:** Previous release 

**Repro Steps:**

1. Expand the Application Settings node.
2. F1 -> Azure Static Web Apps: Delete Setting... -> Select subscription -> Select a static web app -> Select an environment -> Select an app setting -> Enter.
3. Check whether the deleted app setting auto disappears.

**Expect:**
The deleted app setting auto disappears.

**Actual:**  
The deleted app setting doesn't auto disappear.

**More Info:**

1. This issue also reproduces after executing "Azure Static Web Apps: Delete Environment..." from command palette.
2. It is **unstable** that the app setting doesn't auto refresh after executing "Azure Static Web Apps: Add New Setting.../Edit Setting.../Rename Setting..." from command palette.

**Comment by alexweininger** [comment]
@v-xinda Can you check to see if this still reproduces on the latest release of Azure Resources (0.7.1)?

**Comment by v-xinda** [comment]
@alexweininger  Verified this issue with the latest build 20230404.2 and Azure Resources (0.7.1), it doesn't reproduce for now. So I close it.
