### ISSUE TITLE
access issues for static web pages.

### ISSUE THREAD

**Issue by suridatta** [microsoft/vscode-azurestaticwebapps#826]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.activate
Error type: string
Error Message: Timed out waiting for authentication provider to register

Version: 0.11.4
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.68.1
Language: en

**Comment by nturinski** [comment]
Please provide repro steps.
