### ISSUE TITLE
There is no "GitHub Configuration" node under the "Production" node after creating a static web app

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#842]
**OS:** All
**Build Version:** 20230626.2
**Regression:** Previous release (0.11.4)

**Repro Steps:**
1. Open the `ReactSite` project in VS Code.
2. Create a static web app -> Expand it -> Expand "Production" node.
3. Check whether there is "GitHub Configuration" node under the "Production" node.

**Expect:**
There is "GitHub Configuration" node under the "Production" node.
![image](https://github.com/microsoft/vscode-azurestaticwebapps/assets/57662131/f66bde89-a9b9-4a6e-a235-bcb04479be92)

**Actual:**
There is no "GitHub Configuration" node under the "Production" node.
![image](https://github.com/microsoft/vscode-azurestaticwebapps/assets/57662131/b4de7cc8-9913-4112-b7f2-4f00746cdd01)

**Comment by alexweininger** [comment]
In my testing, this is also broken in the current release.
