### ISSUE TITLE
server js

### ISSUE THREAD

**Issue by maksimdev16** [microsoft/vscode-azurestaticwebapps#848]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.activate
Error type: string
Error Message: Timed out waiting for authentication provider to register

Version: 0.12.2
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code - Insiders
Product Version: 1.81.0-insider
Language: en

**Comment by nturinski** [comment]
Closing as a duplicate of https://github.com/microsoft/vscode-azurestaticwebapps/issues/850
