### ISSUE TITLE
i cannot deploy static app from VS

### ISSUE THREAD

**Issue by hadeerhma** [microsoft/vscode-azurestaticwebapps#859]
Does this occur consistently? 
Repro steps:

1.Error running command staticWebApps.createStaticWebApp: command 'staticWebApps.createStaticWebApp' not found. This is likely caused by the extension that contributes staticWebApps.createStaticWebApp.
2. also create Http function not exist

Action: staticWebApps.activate
Error type: string
Error Message: Timed out waiting for authentication provider to register

Version: 0.12.2
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.81.1
Language: en

**Comment by nturinski** [comment]
Hi, it looks like the extension isn't activating for some reason. The authentication provider that we use is the `GitHub Authentication Provider`.

This [comment](https://github.com/microsoft/vscode-pull-request-github/issues/3469#issuecomment-1109584285) has a fix for this issue. It seems like you may have to go and enable GitHub Authentication.

Please let me know if this resolves your issue.
