### ISSUE TITLE
Failed to setup project: write EPROTO 84630000:error

### ISSUE THREAD

**Issue by pmarkonda369** [microsoft/vscode-azurestaticwebapps#862]
whle deploying static app into Azure, encountered below error. Please help.

✖ Failed to setup project: write EPROTO 84630000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:922:

**Comment by alexweininger** [comment]
Can you please add detailed steps for how to reproduce the issue?
