### ISSUE TITLE
Zanega Browser 

### ISSUE THREAD

**Issue by Z-zanega** [microsoft/vscode-azurestaticwebapps#863]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.activate
Error type: string
Error Message: Timed out waiting for authentication provider to register

Version: 0.12.2
OS: undefined
OS Release: 5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36
Product: Visual Studio Code
Product Version: 1.82.2
Language: ar-eg

**Comment by alexweininger** [comment]
Does this reproduce consistently?
