### ISSUE TITLE
[Bug] Azure Static Web Apps Extension, bad credentials error message

### ISSUE THREAD

**Issue by softchris** [microsoft/vscode-azurestaticwebapps#865]
I am using the VS Code extension with latest VS Code insiders on macOS and latest extension updates. I'm getting this error below:

![image](https://github.com/microsoft/vscode-azurestaticwebapps/assets/4598064/bcec1df7-81a5-4bf6-b232-2453b5026ebd)

**Comment by nturinski** [comment]
Sorry for the late reply. If you're still experiencing this issue, could you give us some more information about the repository/SWA that you're trying to access? 

It seems like the Azure credentials are correct, but something is preventing you from looking at the GitHub repository. Maybe you're not an owner?

Has this ever worked for you before and does it happen consistently to you now?
