### ISSUE TITLE
fix?

### ISSUE THREAD

**Issue by talju0** [microsoft/vscode-azurestaticwebapps#876]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.activate
Error type: string
Error Message: Timed out waiting for authentication provider to register

Version: 0.12.2
OS: darwin
OS Release: 23.2.0
Product: Visual Studio Code
Product Version: 1.85.1
Language: en

**Comment by nturinski** [comment]
Please follow the comment here for a potential fix: https://github.com/microsoft/vscode-pull-request-github/issues/3469#issuecomment-1109584285

If this doesn't help resolve your issue, please provide repro steps.
