### ISSUE TITLE
Error while hosting static web app

### ISSUE THREAD

**Issue by Adhisha-21** [microsoft/vscode-azurestaticwebapps#878]
Does this occur consistently? 
Repro steps:

1. actual result : https://lemon-bay-0d4145800.4.azurestaticapps.net/
2. expected result : the code with changes has to be executed

Action: staticWebApps.createStaticWebApp
Error type: GitError
Error Message: Git: From redacted:url

Version: 0.12.2
OS: linux
OS Release: 6.2.0-1018-azure
Product: Visual Studio Code
Product Version: 1.85.2
Language: en

<details>
<summary>Call Stack</summary>

```
handleGitError extension.bundle.js:2:2491652
extension.bundle.js:2:2539318
rejected extension.bundle.js:2:2532115
```

</details>

**Comment by MicroFish91** [comment]
Could you please provide repro steps.  Also, do you have git installed?  You'll need git installed to deploy your static web app.
