### ISSUE TITLE
Voice Recognition

### ISSUE THREAD

**Issue by alfredordgzs** [microsoft/vscode-azurestaticwebapps#885]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.activate
Error type: string
Error Message: Timed out waiting for authentication provider to register

Version: 0.12.2
OS: win32
OS Release: 10.0.22631
Product: Visual Studio Code
Product Version: 1.87.0
Language: en

**Comment by nturinski** [comment]
Please add repro steps and details about your issue. Our extension does not offer any type of voice recognition module.

**Comment by alfredordgzs** [comment]
All Is well done, thank you
