### ISSUE TITLE
Handle restricted app settings

### ISSUE THREAD

**Issue by annaji-msft** [microsoft/vscode-azurestaticwebapps#89]
Below startswith patterns are restricted app settings in static web app functions

^APPINSIGHTS_,^APPSETTING_,^AZUREBLOBSTORAGE_,^AZUREFILESSTORAGE_,^AZURE_FUNCTION_,^CONTAINER_,^DIAGNOSTICS_,^DOCKER_,^FUNCTIONS_,^IDENTITY_,^MACHINEKEY_,^MAINSITE_,^MSDEPLOY_,^SCMSITE_,^SCM_,^WEBSITES_,^WEBSITE_,^WEBSOCKET_,^AzureWeb

The flow gives impression that they could be added
![image](https://user-images.githubusercontent.com/42851022/82108941-6091c880-96e7-11ea-9213-ab3a8d3c57ac.png)

**Comment by anthonychu** [comment]
@annaji-msft Is the plan still to have the extension validate?

**Comment by nturinski** [comment]
@annaji-msft  I haven't been seeing these settings in the extension anymore.  Is the platform not returning these anymore in the API calls?

**Comment by nturinski** [comment]
I'm going to go ahead and close due to the following reasons:
1. Not seeing this behavior anymore.  The settings seemed to be stifled at the platform level
2. Lack of activity from @annaji-msft to state otherwise.

Of course, I always reserve the right to be wrong so please reopen if so 😃

**Comment by jarmanso7** [comment]
Please see the[ constraints in Managed Azure Functions for Azure Static WebApps](https://docs.microsoft.com/en-us/azure/static-web-apps/apis#constraints) in the docs.
