### ISSUE TITLE
hvv

### ISSUE THREAD

**Issue by havv-777** [microsoft/vscode-azurestaticwebapps#890]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.activate
Error type: string
Error Message: Timed out waiting for authentication provider to register

Version: 0.12.2
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.87.2
Language: en

**Comment by nturinski** [comment]
Please provide repro steps and detailed information about your issue.
