### ISSUE TITLE
Static Web App: Bad Credentials error

### ISSUE THREAD

**Issue by mklappdesign** [microsoft/vscode-azurestaticwebapps#891]
Does this occur consistently? Yes
Repro steps:

1. Right click Static Web Apps
2. Click Create Static Web App

Action: staticWebApps.createStaticWebApp
Error type: 401
Error Message: Bad credentials

Version: 0.12.2
OS: win32
OS Release: 10.0.19045
Product: Visual Studio Code
Product Version: 1.88.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:2:1688784extension.bundle.js:2:1688784
```

</details>

**Comment by nturinski** [comment]
Could you provide more details? Are you logged into your GitHub account through VS Code? Maybe try signing out and signing back in since it seems like your credentials may be bad.
