### ISSUE TITLE
No step "Select a .NET runtime" during creating a C# HTTP Function 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#899]
**OS:** All
**Build Version:** 0.12.3-alpha.0
**Regression:** Not a regression

**Repro Steps:**

1. Open the empty folder in VS Code.
2. F1 -> Click "Azure Static Web Apps: Create HTTP Function..." -> Select **C#** language.
3. Check whether the next step is "Select a .NET runtime".

**Expect:**
The next step is "Select a .NET runtime", like below:
![image](https://github.com/microsoft/vscode-azurestaticwebapps/assets/57662131/791cd251-0d90-4bf1-be2c-02c1edd485d8)

**Actual:**
No step "Select a .NET runtime".

**More Info:**
The default .NET version is 6.0 after creating a C# HTTP Function.
<img width="699" alt="Screenshot 2024-05-31 at 15 29 09" src="https://github.com/microsoft/vscode-azurestaticwebapps/assets/57662131/6d8e9b44-f377-41cd-8467-d2d54fe1c358">

**Comment by nturinski** [comment]
Should be resolved with Megan's PR above. It will be fixed with the next function's release so closing for now.
