### ISSUE TITLE
azure login issue through visual studio code cli

### ISSUE THREAD

**Issue by developerbaba443** [microsoft/vscode-azurestaticwebapps#910]
Checking Azure session...
✖ Failed to setup project: this.keychainCache.findCredentials is not a function

I have already azure login in browser. But throwing above error.

**Comment by nturinski** [comment]
This static web apps CLI is not controlled by the VS Code extension.

Please file your issue here: https://github.com/Azure/static-web-apps-cli/issues

**Comment by developerbaba443** [comment]
> The static web apps CLI is not controlled by the VS Code extension.
> 
> Please file your issue here: https://github.com/Azure/static-web-apps-cli/issues

I am using SWA cli and command.
>swa login
>swa deploy
then throwing error:
Checking Azure session...
✖ Failed to setup project: this.keychainCache.findCredentials is not a function
