### ISSUE TITLE
Fail to create a static web app

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurestaticwebapps#912]
**OS:** Win 10
**Build Version:** 20240727.1

**Repro Steps:**

1. Open the [ReactSite](https://github.com/nturinski/ReactSite) project in VS Code.
2. F1 -> Azure Static Web Apps: Create Static Web App... -> Enter a name -> Select a region -> Select "Custom" -> Type "app" -> "build".
3. Check whether succeeds to create a static web app.

**Expect:**
Succeed to create a static web app.

**Actual:**
Fail to create a static web app.
<img width="305" alt="image" src="https://github.com/user-attachments/assets/f33ac720-32c7-46ba-b519-cd4653081ec2">

**More Info:**
This issue also reproduces on the current released Azure Static Web Apps extension v0.12.2, but it didn't reproduce when doing Azure Static Web Apps extension regular testing before.

**Comment by nturinski** [comment]
I don't think anything would have changed. Could you try this again? I think it may have been a temporary outage with either GitHub Actions or Static Web Apps.

**Comment by v-chenzha** [comment]
Verified this issue on released Azure Static Web Apps extension v0.12.2, it still reproduces.
![image](https://github.com/user-attachments/assets/0e5778d3-7317-4a01-8e24-7dcfcceb9344)

**Comment by alexweininger** [comment]
The testing template fails to build when using Node 18. This repros locally and in the GH Action. https://github.com/alexweininger/ReactSite/actions/runs/12166609900/job/33933245377

**Comment by alexweininger** [comment]
@nturinski run `npm audit fix --force` on the ReactSite repo in the /app directory to fix the issue. I would but I don't have access to your repo and my fork is based on a different base.

**Comment by nturinski** [comment]
Should be done. Please retest with this repo after pulling down the changes from `master`.

**Comment by v-chenzha** [comment]
Verified this issue on the latest build 20241125.1, it doesn't reproduce for now.
![Image](https://github.com/user-attachments/assets/1a95ecf9-a295-4c6d-8391-4ee2e9d858e7)

**Comment by nturinski** [comment]
Okay, will go ahead and close this.
