### ISSUE TITLE
[Github Codespace] The Azure Static Web Apps icon is not visible in workspace view

### ISSUE THREAD

**Issue by Amar-QA** [microsoft/vscode-azurestaticwebapps#913]
**Environment:** Remote Codespace
**Release Version:** Current Release v0.12.2

**Repro Steps:**

1. Install the current released Azure Static Web Apps extension.
2. Navigate to the workspace view.
3. Check whether the Azure Static Web Apps icon is visible in workspace view.

**Expect:**
The Azure Static Web Apps icon is visible in workspace view.
![image](https://github.com/user-attachments/assets/de9b2259-e741-424e-b66b-813288e66f83)

**Actual:**
The Azure Static Web Apps icon is not visible in workspace view.
![image](https://github.com/user-attachments/assets/172d4587-a6fe-495e-88ae-073de097e452)

**More Info:**
**1. This issue does not reproduce in the latest main branch build (20240727.1).**
2. This issue only occurs in the remote Codespace environment.

**Comment by nturinski** [comment]
This should be fixed already, we just need to release.
