### ISSUE TITLE
Debugging StaticWebApps (Including Functions) Locally

### ISSUE THREAD

**Issue by annaji-msft** [microsoft/vscode-azurestaticwebapps#94]
Would be nice to have an experience to debug both locally hosted static content and functions together. 

Atleast documenting some recipes similar to 
https://code.visualstudio.com/docs/nodejs/debugging-recipes can go long ways.

**Comment by nturinski** [comment]
> Atleast documenting some recipes similar to
https://code.visualstudio.com/docs/nodejs/debugging-recipes can go long ways.

It seems more likely that we'll go this route.  It'd be difficult to special-case logic all of the different types of frameworks that are available to create a working launch.json

**Comment by nturinski** [comment]
@fiveisprime @anthonychu What channels should I go through to documentation on how to set up local debugging in VS Code?

Or is this worth punting until we get the local emulator experience where we want it to be?

**Comment by alexweininger** [comment]
Not a blocker but tracking: https://github.com/microsoft/vscode/issues/136250

**Comment by alexweininger** [comment]
We just released a debugging feature in the latest version (0.9.0) of the extension. Find out more about this feature in [Guide: Debugging a Static Web App with VSCode](https://github.com/microsoft/vscode-azurestaticwebapps/wiki/Guide:-Debugging-a-Static-Web-App-with-VS-Code).
