### ISSUE TITLE
Add staticwebapp.config.json command

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-azurestaticwebapps#97]
Create a command that adds the staticwebapp.config.json file.

**Comment by nturinski** [comment]
Similar to this issue: https://github.com/microsoft/vscode-azurestaticwebapps/issues/94, we feel like creating the routes.json for the user would be pretty unmaintainable since it will be framework specific when they deploy the SWA.

Also similarly, we should probably just direct them to another recipes page on how to set up their routes depending on which framework they are using.

**Comment by johnpapa** [comment]
It would be easy to set up a default rule in a snippet that they can enter the route and the page to return. Those could default to index.html but be a placeholder in a snippet. 

A snippet is far better experience than going to docs. Creating the file is even better. 

Don’t need to create the file automatically but a command to add it would be super friendly.

**Comment by anthonychu** [comment]
@wwlorey FYI we also added the schema that should help with intellisense in the file: https://github.com/SchemaStore/schemastore/pull/1551

> @nturinski: Similar to this issue: #94, we feel like creating the routes.json for the user would be pretty unmaintainable since it will be framework specific when they deploy the SWA.

This is much better now. The recommendation is for staticwebapp.config.json to be at the root fold of their frontend app, but we will search for it in any subfolder.

@johnpapa Is the intention of this to simplify adding a fallback route? For that, it's such a common task that I think we should add an explicit gesture.

I suggest changing this issue to add an "Add default fallback route" command. Something like:
* Ask for the root of the frontend app
* If staticwebapp.config.json doesn't exist in the folder or subfolders, add one at the root with the default fallback route
* If staticwebapp.config.json exists
    * If there's no `navigationFallback` section, add the default
    * If there's already a `navigationFallback` section, error
* If more than one staticwebapp.config.json exists, this is not good in general
* Maybe support a context menu item for this command when right-clicking a folder or existing staticwebapp.config.json

Default fallback route:
```json
  "navigationFallback": {
    "rewrite": "/index.html"
  }
```

**Comment by johnpapa** [comment]
Good question @anthonychu 

I think a fallback is a big reason this would be nice. So yes, your plan could be very helpful. 

Could these both be good thought? user wants to create routes of any kind. They find a command that creates the file (empty) and the schema is applied. User wants to add a 401 page, or a fallback route, or some other common routing logic ... this could be solved with commands or snippets.

**Comment by anthonychu** [comment]
Yep. I was trying to point out that having the schema in place already provides the autocomplete and validation that I think we're looking for:

![swa-config-schema](https://user-images.githubusercontent.com/3982077/113921694-274cc600-979b-11eb-9567-0bd88cbc40ef.gif)

So I'm thinking this extension can help specifically to address creating a config file and seeding it with a fallback route.

**Comment by anthonychu** [comment]
Now that I read this again... just realized this issue _is_ already for the creation of the config file. I was confusing it with #98.
