### ISSUE TITLE
Add snippets for adding fallback route to  routes.json

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-azurestaticwebapps#98]

**Comment by nturinski** [comment]
Hi @johnpapa

Could you give me some more details about what the feature request is?  I'm not really sure what this entails.

**Comment by johnpapa** [comment]
Sure.  The routes.json file is in our docs at https://aka.ms/swadocs 

We can add a fallback route to this array. The fallback will catch 404 server errors and serve the index.html, commonly. 

I could provide the snippet if it is helpful.

**Comment by nturinski** [comment]
Yes, the snippet would be helpful 😄 

My experience with SWA is still pretty limited so any bigger examples beyond the ReactSite repo would also be greatly appreciated!

**Comment by johnpapa** [comment]
Here you go. Sorry for the delay

```
	"SWA Fallback Routes": {
		"prefix": "swa-fallback",
		"body": [
			"{$0",
			"\t\"routes\": [",
			"\t\t{",
			"\t\t\t\"route\": \"/*\",",
			"\t\t\t\"serve\": \"/index.html\",",
			"\t\t\t\"statusCode\": 200",
			"\t\t}",
			"\t]",
			"}",
		]
	},
```

**Comment by aartigh** [comment]
Hi Team,

My reactjs app is deployed in Azure Static Web App(preview).

My website url : www.example.com shows all images render properly from public folder. 
From home page, if user navigate to https://www.example.com/nextpage/page1 then still it shows all the images properly.

But if user, refresh or navigate to https://www.example.com/nextpage/page1 directly then images are not rendered, gives 404 error. 

my routes.json file in public folder looks like below

{
  "routes": [
    {
      "route": "/*",
      "serve": "/index.html",
      "statusCode": 200
    }
  ]
}

Appreciate your help.

**Comment by anthonychu** [comment]
@aartigh can you please file an issue at https://github.com/Azure/static-web-apps/issues ?

Please include info on how the `img` tag is formed and the error in your browser dev tools. If you have a live site that is public and we can troubleshoot, please include that too. Thanks!

**Comment by aartigh** [comment]
@anthonychu thanks, if you access https://www.skillsandautomation.com/blog/B1 url directly, you can see image at top left not rendered, gives 404 error in dev tool. Whereas if we access the https://www.skillsandautomation.com, image at top left is rendered correctly.

**Comment by aartigh** [comment]
@anthonychu my issue is resolved, i have change way of specifying that image path.

**Comment by anthonychu** [comment]
@nturinski @wwlorey I think this is covered by https://github.com/SchemaStore/schemastore/pull/1551, which adds example snippets for fallback and other sections, intellisense, and validation:

![swa-config-schema](https://user-images.githubusercontent.com/3982077/113929675-3173c200-97a5-11eb-809c-90d0b761315a.gif)

Regarding staticwebapp.config.json vs routes.json, we're recommended folks use staticwebapp.config.json, so I don't think we need to do much more for routes.json.
